lib/js_service_encointer/.babelrc
lib/js_service_encointer/jest.config.js
lib/js_service_encointer/package.json
lib/js_service_encointer/src/index.js
lib/js_service_encointer/src/service/account.js
lib/js_service_encointer/src/service/encointer.js
lib/js_service_encointer/src/service/encointer.test.js
lib/js_service_encointer/src/utils/fixpointUtil.js
lib/js_service_encointer/webpack.config.js
lib/js_service_encointer/yarn.lock

Implementation of #10, #11, #12 
Function `getProofOfAttendance`  described in JSdoc.
`@polkadot/api` and `@polkadot/ui-shared` got deps upgraded, hope it didn't brake anything.

Add getProofOfAttendance in js_service

---

lib/js_service_encointer/src/config/types.js
lib/js_service_encointer/src/service/encointer.js
lib/js_service_encointer/src/service/encointer.test.js
lib/service/substrateApi/encointer/apiEncointer.dart

- add encointer.parseAttestation(attestationHex) 
- fix all unit tests except getClaimOfAttendance on js side

add-encointer.parseAttestation

---

lib/js_service_encointer/package.json
lib/js_service_encointer/src/service/worker.js
lib/js_service_encointer/src/service/worker.test.js

JS: Integration tests for worker-api

---

lib/common/consts/settings.dart
lib/js_service_encointer/package.json
lib/js_service_encointer/src/index.js
lib/js_service_encointer/src/index.test.js
lib/js_service_encointer/src/service/worker.js
lib/js_service_encointer/src/service/worker.test.js
lib/service/substrateApi/api.dart
lib/service/substrateApi/encointer/apiEncointer.dart
lib/store/settings.dart

- setup testing for worker api, worker api is buggy. see #30 
- basic skeleton to integrate worker with dart

Integrate worker api for cantillon support

---

lib/js_service_encointer/src/index.test.js
lib/js_service_encointer/src/service/encointer.js
lib/page/assets/index.dart
lib/service/substrateApi/api.dart
lib/service/substrateApi/apiAssets.dart
lib/service/substrateApi/encointer/apiEncointer.dart
lib/store/encointer/encointer.dart
lib/store/encointer/encointer.g.dart
lib/store/encointer/types/attestation.dart
lib/store/encointer/types/attestationState.dart
lib/store/encointer/types/claimOfAttendance.dart
lib/store/encointer/types/encointerBalanceData.dart
lib/store/encointer/types/encointerBalanceData.g.dart
lib/store/encointer/types/location.dart
lib/store/settings.g.dart
lib/store/staking/staking.g.dart

- added  `encointer.getBalances` that fetches the balance of current account for all encointer balances
- show encointerBalances in index
**Note:** For some reason the balances show up only after switching **twice** from and to the index window. As
1. the first time encointer.getBalances is not called for some reason....
2. the second time the observable does not properly update the widget....

Show encointer balances

---

lib/js_service_encointer/package.json
lib/js_service_encointer/src/index.test.js
lib/js_service_encointer/src/service/account.js
lib/js_service_encointer/src/service/encointer.test.js
lib/js_service_encointer/yarn.lock
lib/page/assets/index.dart
lib/service/substrateApi/encointer/apiEncointer.dart
lib/utils/i18n/encointer.dart

- added faucet that sends 0.001 ERT to selected account if balance < 0.0001 ERT. Closes #20 
- downgraded polkadot/api dependency to fix #38

Implement faucet

---

lib/page/assets/index.dart

fix showing of encointer balance. Was only a format error.

---

lib/app.dart
lib/common/consts/settings.dart
lib/js_service_encointer/package.json
lib/js_service_encointer/src/service/account.js
lib/js_service_encointer/src/service/encointer.js
lib/js_service_encointer/src/utils/fixpointUtil.js
lib/js_service_encointer/src/utils/fixpointUtil.test.js
lib/js_service_encointer/yarn.lock
lib/page-encointer/assigning/assigningPage.dart
lib/page-encointer/attesting/attestingPage.dart
lib/page-encointer/attesting/qrCode.dart
lib/page-encointer/common/CeremonyOverviewPanel.dart
lib/page-encointer/common/assignmentPanel.dart
lib/page-encointer/common/currencyChooserPanel.dart
lib/page-encointer/registering/registeringPage.dart
lib/page/assets/asset/assetPage.dart
lib/page/assets/index.dart
lib/page/assets/receive/receivePage.dart
lib/page/assets/transfer/transferPage.dart
lib/page/networkSelectPage.dart
lib/service/substrateApi/apiAssets.dart
lib/store/encointer/encointer.dart
lib/store/encointer/types/encointerBalanceData.dart
lib/store/encointer/types/encointerBalanceData.g.dart
lib/store/settings.dart
lib/store/settings.g.dart
lib/utils/format.dart

With a click on the respective EncointerCommunityCurrency in the AssetPage, the respective currency can now be transferred.  Closes #44 
Other things:
* Includes dependency fixes on JS side - removed a lot of duplicates. JS blob is now only 2.4 MiB (compared to 6.4 MiB before)
* Adds encoding of floatToFixedPoint on JS side. Closes #49

Community currency wallet functionality

---

lib/js_service_encointer/src/service/encointer.js
lib/page-encointer/attesting/attestingPage.dart
lib/page-encointer/common/assignmentPanel.dart
lib/service/substrateApi/encointer/apiEncointer.dart

Meetup location and time fix

---

lib/common/components/activityIndicator.dart
lib/page-encointer/attesting/attestationCard.dart

Not happy yet with the design of the activityIndicator, but it works for now.
Performed two meetups. With the removal of the parseAttestation/Claim there is hardly any hanging of the meetup. Closes #67

Improve meetup ux

---

pubspec.lock
pubspec.yaml

Did not test meetup afterwards, but transfer works.

remove some unused dependencies with the help of dependency_validator

---

CHANGELOG.md
lib/common/components/passwordInputDialog.dart
lib/js_service_encointer/src/service/account.js
lib/page-encointer/meetup/MeetupPage.dart
lib/page-encointer/phases/registering/registerParticipantPanel.dart
lib/page/account/create/createAccountForm.dart
lib/page/assets/index.dart
lib/page/profile/account/changePasswordPage.dart
lib/page/profile/account/exportAccountPage.dart
lib/service/substrateApi/encointer/apiEncointer.dart
lib/utils/format.dart
lib/utils/i18n/account.dart
lib/utils/i18n/encointer.dart

* Meetup: Show note that a password is needed if no password was entered in the dialog and return to the ceremony page.
Tested with a successful meetup.

Use pin instead of password to unlock account + some small fixes

---

lib/js_service_encointer/src/service/account.js
lib/page/assets/asset/assetPage.dart
lib/store/encointer/encointer.dart

* Fix #54 : Show tx-history with with correct fixpoint values
* Remove cid from the transferlist item. only display it in the appbar.
* add some header to tx-list: "from/to" and "amount"

#54/tx history improvement

---

.github/action-config.json
lib/main.dart
lib/page-encointer/bazaar/common/imagePickerHandler.dart
lib/page-encointer/meetup/attestation/components/scanQrCode.dart
lib/page/account/scanPage.dart
lib/service/notification.dart
lib/service/subscan.dart
lib/service/walletApi.dart
pubspec.lock
pubspec.yaml
test_driver/app_test.dart

Update flutter deps

---

lib/js_service_encointer/src/service/encointer.js
lib/service/substrateApi/encointer/apiEncointer.dart
lib/store/encointer/encointer.dart
lib/store/encointer/types/encointerTypes.dart

Improve getNextMeetupTime response time and fix negative numbers in its return value

---

lib/store/account/account.dart
pubspec.lock
pubspec.yaml

Remove one blocker for null-safety migration #139

Fix flutter tests

---

.github/action-config.json
.github/workflows/android_build.yml
.github/workflows/android_integration_test.yml
.github/workflows/ios_integration_test.yaml
lib/js_service_encointer/.browserslistrc
lib/js_service_encointer/package.json
lib/js_service_encointer/scripts/buildWebpack.cjs
lib/js_service_encointer/yarn.lock
pubspec.lock
pubspec.yaml
scripts/build_js.sh

* Pin exact node/yarn version in CI
* Print some extra info when building js
* Cancel previous CI jobs upon push

Some CI + dev-experience improvements

---

.github/workflows/android_integration_test.yml
.github/workflows/ios_integration_test.yaml
scripts/ios_init_env.sh

[GA] fix IOS-emulator setup + remove very flaky android api 29 emulator

---

lib/page/assets/index.dart
lib/page/networkSelectPage.dart

Remove Cantillon endpoints + don't show password dialogs on main page for Gesell

---

.github/workflows/fdroid.yml
scripts/fdroid_init.sh

It runs successfully in the GA CI. I reckon it should work in the fdroid pipeline too.
I still went for the script approach because it seemed fairly straight-forward.
merged f-droid companion: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10190

Fix fdroid build

---

lib/page/assets/index.dart

closes #251
* Show currently chosen network and navigate to network selection page … 
* Show current account as an icon, open account settings on tap

AssetsView: Show currently chosen network and show account as icon

---

lib/page-encointer/common/communityChooserOnMap.dart
lib/page-encointer/common/communityChooserPanel.dart
lib/store/encointer/types/communities.dart
pubspec.lock
pubspec.yaml
test_driver/app_test.dart

* closes #277 
* Add a community selector showing pins on the map

Armin 277 community selection on a map

---

ios/Flutter/AppFrameworkInfo.plist

Fix iOS App Store build architecture warning

---

lib/page/profile/index.dart

Closes #311 
* show status of connection to network

Add network connection status spinner or check mark

---

lib/common/theme.dart
lib/page-encointer/homePage.dart
lib/page/assets/index.dart

* Closes #302 
* did the design with the background first, but there is no way to reduce padding of the navbar, as the UI elements increased b/c of the background which is bigger than the icon
* changed the design to using a darker color to highlight the Scan icon (Didier first suggested to use blue, before he suggested to use a background color, the issue with blue was that it looks like Scan was already selected)
version: **light blue container**
version: **light blue container minimum sized container, but then hardly visible**
version: **dark blue stroke of the scan icon, currently implemented**

Add NavBar Design

---

lib/common/theme.dart
lib/page/assets/index.dart
lib/utils/i18n/assets.dart

* Add a theme for the AppBar as designed by Didier
* can be reused across the app, we can use what the framework provided but tailor its design to our needs
* adhere to the DRY principle
* Closes #319

Add AppBar theme

---

lib/common/components/AddressInputField.dart
lib/common/components/encointerTextFormField.dart
lib/common/theme.dart
lib/page-encointer/common/communityChooserPanel.dart
lib/page/assets/index.dart
lib/page/assets/receive/receivePage.dart
lib/page/assets/transfer/transferCrossChainPage.dart
lib/page/assets/transfer/transferPage.dart
lib/utils/UI.dart
lib/utils/i18n/assets.dart
lib/utils/i18n/profile.dart
test_driver/app_test.dart

* closes issue #303 
* implemented the layout for payments as designed by Didier
* generating the QR code and sharing it is new functionality which is left to do in another PR

[Design] send and receive page

---

lib/page/account/import/importAccountForm.dart

Fix bug on importAccountForm.dart (crash b/c of widget being null)

---

lib/page-encointer/common/communityChooserOnMap.dart

Fix duplicate key bug

---

lib/js_service_encointer/test/gesell.test-e2e.js
lib/store/encointer/encointer.dart
lib/store/encointer/encointer.g.dart
lib/store/encointer/types/communities.dart
test/store/types/communities_test.dart

Fix CommunityIdentifier equality

---

lib/page-encointer/homePage.dart
lib/page/profile/index.dart
lib/store/settings.dart
lib/store/settings.g.dart
lib/utils/translations/translationsProfile.dart

Hide bazaar by default, but add option to enable it in developer options.

---

lib/page-encointer/meetup/scanClaimQrCode.dart

* Closes #374.
* To be properly solved in #390

skip meetupRegistry verification due to bogus meetupRegistry

---

lib/page/profile/aboutPage.dart
lib/page/profile/index.dart
lib/utils/translations/translationsProfile.dart

* Closes #389.
Changes:
* One can navigate to `AboutPage` from `ProfilePage`
* build number is displayed in the app version.
* Cleanup `AboutPage`

reactivate `AboutPage`

---

lib/page/profile/contacts/accountSharePage.dart

Hotfix contact QR-code scan

---

lib/page/account/scanPage.dart
lib/page/assets/index.dart
lib/page/assets/transfer/transferPage.dart
lib/service/qrScanService.dart
lib/store/encointer/encointer.dart
test/components/qrScanService_test.dart

* Closes #399.
Tested:
* successfully transferred funds with QR-code invoice
* scanning contact does still work

Fix: Send transfer from QR-code invoice

---

pubspec.yaml

bump version to 1.1.1

---

lib/page/account/scanPage.dart

Add close button to scan page

---

lib/page-encointer/bazaar/shared/data_model/demo_data/demoData.dart

unbranding examples

---

lib/page-encointer/common/assignmentPanel.dart
lib/store/encointer/types/location.dart

[assignmentPannel] add location null-check

---

.github/workflows/ios_integration_test.yaml
scripts/ios_init_env.sh

* Closes https://github.com/encointer/encointer-wallet-flutter/issues/449

Fix IOS-CI: switch to patched fork for wix/brew

---

lib/page/profile/account/accountManagePage.dart
lib/page/profile/contacts/contactDetailPage.dart

[contactDetailsPage] enable copy to clipboard of address

---

scripts/ios_init_env.sh

[scripts/ios_init_env] remove obsolete wix/brew fork.

---

lib/common/components/secondaryButtonWide.dart
lib/page/assets/index.dart
lib/page/profile/account/accountManagePage.dart
lib/page/profile/contacts/contactDetailPage.dart
lib/service/substrateApi/encointer/apiEncointer.dart
lib/store/encointer/encointer.dart
lib/utils/translations/translationsProfile.dart
lib/utils/tx.dart

Add option to endorse at contactDetailsPage

---

ios/Runner/Info.plist

[ios] add purpose string for the calendar

---

lib/js_service_encointer/src/service/encointer.js
lib/service/substrateApi/encointer/apiEncointer.dart

This was possible before, as encointer-js supported that already. We just had to remove the assertion in this repository's js-code.
* Closes #470

Enable fetching meetupTime in registering phase

---

lib/page/assets/account_or_community/accountOrCommunityItemHorizontal.dart
lib/page/assets/index.dart
lib/utils/translations/translationsHome.dart

Fix overflow by constraining the text to be max 2 lines display ellipsis in case the text is very long

---

lib/page/assets/index.dart
lib/page/networkSelectPage.dart
lib/service/substrateApi/api.dart
lib/service/substrateApi/encointer/apiEncointer.dart
lib/store/encointer/encointer.dart
lib/store/settings.dart
lib/store/settings.g.dart

more meaningful endpoint classification TeeProxy vs NoTee
with this, a successful ceremony was performed on rococo

fix endpoint checks for parachains

---

lib/mocks/api/accountApi.dart
lib/mocks/api/api.dart
lib/mocks/api/apiAssets.dart
lib/mocks/api/chain.dart
lib/mocks/api/encointerApi.dart
lib/mocks/api/jsApi.dart
lib/service/substrate_api/accountApi.dart
lib/service/substrate_api/api.dart
lib/service/substrate_api/assetsApi.dart
lib/service/substrate_api/chainApi.dart
lib/service/substrate_api/codecApi.dart
lib/service/substrate_api/encointer/encointerApi.dart
lib/service/substrate_api/encointer/noTeeApi.dart
lib/service/substrate_api/encointer/teeProxyApi.dart
lib/service/substrate_api/jsApi.dart

* Closes #518 
It does improve IDE performance, but not to the extent I hoped.
* Edit: #521 improves IDE performance by a great deal again.

Fix cyclic dependencies in `Api`

---

lib/app.dart
lib/page/networkSelectPage.dart
lib/service/substrate_api/api.dart
lib/service/substrate_api/encointer/encointerApi.dart
lib/service/substrate_api/encointer/encointerDartApi.dart

fix network switching #543

---

lib/mocks/data/mockEncointerData.dart
lib/mocks/storage/prepareMockStorage.dart
lib/models/ceremonies/ceremonies.dart
lib/models/ceremonies/ceremonies.g.dart
lib/page-encointer/ceremony_box/ceremonyBoxService.dart
lib/page-encointer/encointerEntry.dart
lib/page/profile/contacts/contactDetailPage.dart
lib/store/encointer/encointer.dart
lib/store/encointer/encointer.g.dart
test/store/encointer/encointer_test.dart

* Reflect changes of https://github.com/encointer/pallets/pull/209
Beware @brenzi: https://github.com/encointer/encointer-wallet-flutter/issues/547

Rename `CeremonyPhase` enum values to CamelCase

---

README.md
lib/page/assets/index.dart
pubspec.yaml

balanceWatchdog: update balance also when decreasing or fresh

---

lib/service/substrate_api/core/dartApi.dart

reconnect dart api when closed

---

lib/page/profile/account/accountManagePage.dart
lib/page/profile/contacts/accountSharePage.dart
lib/store/account/account.dart

This still shows the address hardcoded with the prefix 42.

[accountManagePage] fix showing ss58 prefixed address

---

lib/config/consts.dart
lib/js_service_encointer/src/service/settings.js

This basically removes the refactoring of the redundant code in the settings in JS, should never have done this in the beginning
I don't know what bricked it, but it is fixed now.

Fix node connection

---

lib/store/account/account.dart

@clangenb this commit breaks the startup of a fresh install

[accountStore] fix `getNetworkAddress`

---

lib/store/settings.dart
test/store/settings_test.dart

closes #554 without transitioning existing installs

default to mainnet instead of gesell

---

lib/js_service_encointer/src/service/account.js
lib/js_service_encointer/src/service/settings.js
lib/js_service_encointer/test/service/account.test.js
lib/page-encointer/phases/attesting/attestingPage.dart
lib/page-encointer/phases/registering/registerParticipantPanel.dart
lib/page/assets/index.dart
lib/page/assets/transfer/transferPage.dart
lib/page/profile/contacts/contactDetailPage.dart
lib/store/encointer/encointer.dart
lib/utils/tx.dart

* Closes #269
Tested so far:
* Alice could register without CC
* Alice sent Ferdie 0.08 CC (Ferdie has no native tokens)
* Ferdie could send 0.4 CC to Eve. Eve was successfully endowed according to polkadot-js
* Ferdie could successfully register for the next ceremony.
Extrinsics not tested so far:
* submittingClaims
* endorseNewcomer
* claimingRewards

Fee payment in community currency

---

android/app/src/main/AndroidManifest.xml
ios/Runner/Info.plist
lib/config/consts.dart
lib/js_service_encointer/src/service/encointer.js
lib/page-encointer/ceremony_box/ceremonyBox.dart
lib/page-encointer/ceremony_box/ceremonyBoxService.dart
lib/page-encointer/ceremony_box/ceremonyInfo.dart
lib/page-encointer/ceremony_box/components/ceremonyCountDown.dart
lib/page-encointer/ceremony_box/components/ceremonyInfoAndCalendar.dart
lib/page-encointer/ceremony_box/components/ceremonyProgressBar.dart
lib/page-encointer/ceremony_box/components/ceremonySchedule.dart
lib/service/substrate_api/encointer/encointerApi.dart
lib/store/encointer/encointer.dart
lib/store/encointer/encointer.g.dart
lib/utils/UI.dart
pubspec.lock
pubspec.yaml
test/store/encointer/encointer_test.dart

Changes in this PR:
* Extract `CeremonyInfoBox` out of the `CeremonyBox`, is the upper part of the `CeremonyBox`, which is entirely passive.
* Integrate the state logic into the `CeremonyInfo` box.
In the next PR, I will extract the lower part of the `CeremonyBox` into the `CeremonyActionBox` and implement the state logic there. This which is the part the user interacts with to register, start meetup, etc.

Implement state logic for CeremonyInfoBox

---

lib/page-encointer/ceremony_box/ceremonyBox.dart
lib/page-encointer/ceremony_box/ceremonyInfo.dart
lib/page-encointer/ceremony_box/components/ceremonyInfoAndCalendar.dart
lib/page/profile/account/accountManagePage.dart

* Closes #585
* Hide calendar behind dev mode

1.50 Fixes

---

lib/page/assets/index.dart

Fix scrolling down to bottom of ceremony box

---

lib/page/assets/index.dart
lib/service/substrate_api/encointer/encointerApi.dart

closes #609
closes #615 
best to test with putting emulator in airplane mode and back
null and error are not the same :rofl:

fix #615 and similar ugly error handling

---

lib/page/assets/index.dart
lib/page/assets/transfer/transferPage.dart
lib/page/profile/account/accountManagePage.dart
lib/page/profile/account/exportAccountPage.dart
lib/page/profile/contacts/contactDetailPage.dart
lib/utils/translations/translationsAssets.dart
lib/utils/translations/translationsEncointer.dart
lib/utils/translations/translationsProfile.dart

also, remove unimplemented reputation indication for contacts

clean up german translation

---

lib/page-encointer/encointerEntry.dart
lib/page/assets/index.dart
lib/store/encointer/encointer.dart
lib/store/encointer/encointer.g.dart

Changes:
* Fix `update_state` function to update all necessary data
* Use pull down gesture on main page to update data.

[CeremonyBox] fix data refresh

---

android/build.gradle
lib/common/components/wakeLockAndBrightnessEnhancer.dart
lib/page-encointer/meetup/ceremonyStep2Scan2.dart
lib/page/assets/receive/receivePage.dart
lib/page/profile/contacts/accountSharePage.dart
pubspec.lock
pubspec.yaml

Enhance screen brightness when showing qr-codes and keep screen awake

---

lib/page/profile/index.dart

I saw how obvious the fix is and could not let it go. :)
* Closes #462

Fix remove all accounts

---

lib/page/qr_scan/qrScanService.dart

closes #668 
it's not the most elegant way to string replace, but certainly very readable and concise.
And the risk of collisions with other payload data is minimal

quick fix redirection of Leu vouchers and invoices

---

lib/service/substrate_api/encointer/encointerApi.dart

fix dynamic meetup time override removal

---

lib/js_service_encointer/src/config/consts.js
lib/js_service_encointer/src/service/account.js
lib/service/tx/lib/src/submitTxWrappers.dart

Fix native token payment asset + properly fix `claimRewards` extrinsic for all possible runtimes

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
ios/Runner/Info.plist

* Closes #711 
The build passes now in the App Center:
https://appcenter.ms/orgs/encointer/apps/Flutter-IOS/build/branches/fix-dep/builds/79

Fix build in app center

---

lib/page-encointer/meetup/scan_claim_qr_code.dart
lib/page/qr_scan/qr_scan_page.dart
lib/utils/translations/translations_home.dart

* We don't really know what is going on on some apple devices when they are trying to get the camera permission, this should help with some diagnostics. Also the user is advised that she can grant permissions from the device settings.

More diagnostics about camera persmissions.

---

analysis_options.yaml
lib/common/components/maybe_date_time.dart
lib/models/communities/community_identifier.dart
lib/models/encointer_balance_data/balance_entry.dart
lib/page-encointer/ceremony_box/components/lower_ceremony_box_container.dart
lib/page/account/import/import_account_form.dart
lib/page/qr_scan/qr_codes/contact.dart
lib/page/qr_scan/qr_codes/invoice.dart
lib/page/qr_scan/qr_codes/qr_code_base.dart
lib/service/ipfs/http_api.dart
lib/service/substrate_api/api.dart
lib/service/substrate_api/assets_api.dart
lib/service/substrate_api/chain_api.dart
lib/service/substrate_api/core/dart_api.dart
lib/service/substrate_api/encointer/encointer_api.dart
lib/store/chain/types/header.dart
lib/store/encointer/encointer.dart
lib/store/encointer/sub_stores/bazaar_store/bazaar_store.dart
lib/store/encointer/sub_stores/community_store/community_account_store/community_account_store.dart
lib/store/encointer/sub_stores/community_store/community_store.dart
lib/store/encointer/sub_stores/encointer_account_store/encointer_account_store.dart

removed unnecessary this expression

---

analysis_options.yaml
lib/service/substrate_api/account_api.dart
lib/utils/translations/index.dart

J prefer if null operators

---

lib/common/components/gr_code_view/gr_code_image_view.dart
lib/utils/extensions/extensions.dart
lib/utils/extensions/layout/layout_extensions.dart

Improve QR-Code size on big devices

---

analysis_options.yaml
lib/app.dart
lib/page/account/import/import_account_form.dart
lib/page/assets/index.dart
lib/service/substrate_api/encointer/encointer_dart_api.dart
lib/store/data_update/data_update.dart

added finals by Lint prefer_final_fields

add lint: `prefer_final_fields`

---

analysis_options.yaml
lib/main.dart
lib/page-encointer/bazaar/menu/2_my_businesses/opening_hours_state.dart
lib/page-encointer/bazaar/shared/data_model/model/bazaar_item_data.dart
lib/service/substrate_api/encointer/encointer_api.dart
lib/utils/format.dart
test_driver/app_test.dart

Lint prefer-interpolation-to-compose-strings

replaced + with $ prefer-interpolation-to-compos-strings

---

analysis_options.yaml
lib/mocks/data/mock_account_data.dart
lib/page-encointer/bazaar/menu/2_my_businesses/businesses_on_map.dart
lib/page-encointer/common/community_chooser_on_map.dart
lib/store/account/account.dart
lib/store/account/types/account_data.dart
lib/store/assets/assets.dart
lib/store/encointer/encointer.dart
lib/store/encointer/sub_stores/encointer_account_store/encointer_account_store.dart
lib/store/settings.dart
test/store/types/communities_test.dart

LInt prefer_collection_literals, used collection literals when it is possible

used collection literals

---

analysis_options.yaml
lib/utils/snack_bar.dart

Linter prefer-equal-for-default-values

prefer_equal_for_default_values

---

lib/page/assets/transfer/transfer_page.dart
lib/page/profile/contacts/contact_detail_page.dart
lib/page/qr_scan/qr_scan_service.dart
lib/page/reap_voucher/reap_voucher_page.dart

* Closes #599 
Tested:
* Does not overwrite if send data invoice data is empty if:
* navigated from home page
* navigated from transfer page
* Does overwrite previous value if invoice data is not empty.

[transfer_page] don't overwrite send amount if invoice data is empty.

---

lib/page-encointer/home_page.dart

* Closes #797. 
I don't think it should lead to any issues.

[push-notifications] do not replace jobs and fix the webView channel with it.

---

.github/action-config.json

Bumb Flutter 3.3.4 .
Just change flutter-version in .github/action-config.json .

Bumb Flutter 3.3.4

---

README.md

Changed Currently supports flutter in README.md file

Currently supports flutter version to 3.3.4

---

README.md
scripts/install_flutter.sh

Tested with appcenter build; works.

Fix appcenter build: bump flutter version in install script

---

lib/page/profile/contacts/contact_page.dart
lib/router/app_router.dart

Fixed automatically strip whitespace in address input field #780.

automatically-strip-whitespace-in-address-input-field

---

lib/utils/translations/index.dart
lib/utils/translations/translations.dart
lib/utils/translations/translations_account.dart
lib/utils/translations/translations_assets.dart
lib/utils/translations/translations_bazaar.dart
lib/utils/translations/translations_encointer.dart
lib/utils/translations/translations_home.dart
lib/utils/translations/translations_profile.dart

changed translations from zh to fr

changed translation from zh to fr

---

lib/modules/splash/view/splash_view.dart
lib/page-encointer/home_page.dart
lib/page/account/create/create_pin_page.dart
lib/page/account/import/import_account_page.dart
lib/router/app_router.dart

fixed: Exception when importing an account on the profile page (seems harmless) #774.

Exception when importing an account

---

lib/js_service_encointer/src/service/account.js
lib/page/assets/index.dart
lib/service/substrate_api/encointer/encointer_api.dart
lib/service/tx/lib/src/params.dart
lib/service/tx/lib/src/submit_tx_wrappers.dart

* Closes #729 
Tested on local setup:

Allow early claim of rewards

---

lib/page-encointer/ceremony_box/ceremony_box.dart
lib/page-encointer/ceremony_box/ceremony_info.dart
lib/page-encointer/ceremony_box/components/ceremony_info_and_calendar.dart

I wand to fix #779, but I saw that there are function codes here.
lib/page-encointer/ceremony_box/components/ceremony_info_abd_calendart.dart
```dart
IconButton(
icon: const Icon(Iconsax.calendar_1),
onPressed: () => Add2Calendar.addEvent2Cal(calendarEventToAdd),
),
```
package: add_2_cal.dart
```dart
class Add2Calendar {
static const MethodChannel _channel = const MethodChannel('add_2_calendar');
/// Add an Event (object) to user's default calendar.
static Future<bool> addEvent2Cal(Event event) async {
return _channel.invokeMethod<bool?>('add2Cal', event.toJson()).then((value) => value ?? false);
}
}
```
And it is work.  [Android](https://raw.githubusercontent.com/Eldar2021/eldar2021.github.io/main/images/Screenshot_1666156545.png) and …

Ceremony add to calendar

---

lib/page-encointer/ceremony_box/ceremony_box_service.dart
lib/page/profile/contacts/contact_detail_page.dart
pubspec.lock
pubspec.yaml

- bump inApp_webView to v6.0.0-beta.11
- fix date in calendar export of gathering time
- fix contact detail page display.

Minor Fixes

---

lib/page/qr_scan/qr_scan_page.dart

Fix Contact Dev-QRCode

---

docker/wallet/000-default.conf
docker/wallet/Dockerfile
docker/wallet/README.md
docker/wallet/apple-app-site-association
docker/wallet/index.html

Added wallet.encointer.org/apple-app-site-association #260

---

analysis_options.yaml
lib/utils/translations/translations_account.dart
lib/utils/translations/translations_assets.dart
lib/utils/translations/translations_bazaar.dart
lib/utils/translations/translations_encointer.dart
lib/utils/translations/translations_home.dart
lib/utils/translations/translations_profile.dart
pubspec.lock
pubspec.yaml

I did integration of the [very_good_analysis](https://pub.dev/packages/very_good_analysis).
I fixed `getter return type` warnings in utils.
All the rest I did `false` so it won’t give us errors.
First we fix `analyzer: language:` and then  `analyzer: errors`, after then other `linter: rules`. 😅

Integration very good analysis

---

lib/js_service_encointer/src/service/encointer.js
lib/page/profile/index.dart
lib/service/tx/lib/src/submit_tx_wrappers.dart

This will help to set up an integration test in the CI that performs a meetup on one device, see #864.

add simple `next-phase` button for the local-dev network

---

pubspec.lock
pubspec.yaml

change git ref: flutter_qr_scan; fixes meetup scanner freeze

---

scripts/fdroid_init.sh

Use gz for node tarball

---

lib/main.dart
lib/utils/translations/index.dart
lib/utils/translations/translations.dart
lib/utils/translations/translations_account.dart
lib/utils/translations/translations_assets.dart
lib/utils/translations/translations_bazaar.dart
lib/utils/translations/translations_encointer.dart
lib/utils/translations/translations_home.dart
lib/utils/translations/translations_profile.dart

did translation to Russian language

J translation to russian

---

ios/Podfile.lock
lib/main.dart
lib/page/assets/transfer/transfer_page.dart
lib/utils/translations/translations_assets.dart

Verify community when sending funds by QR scan or invoice

Verify community when sending funds by QR scan or invoice

---

.github/workflows/android_build.yml
.github/workflows/android_integration_test.yml
.github/workflows/ios_integration_test.yaml
.github/workflows/unit_tests.yaml
lib/main.dart
scripts/android_integration_test.sh
scripts/install_flutter.sh
scripts/ios_integration_test.sh

Flutter wrapper test

---

lib/js_service_encointer/src/service/encointer.js
lib/js_service_encointer/src/service/settings.js
lib/js_service_encointer/test/service/encointer.test.js

Because of: https://github.com/encointer/pallets/pull/274
Tested:
* Pending Issuance V1 works on local network
* Pending Issuance V2 works on local network

Update check for pending issuance for new runtimes

---

.github/action-config.json
.github/workflows/android_build.yml
.github/workflows/android_integration_test.yml
.github/workflows/ios_integration_test.yaml
.github/workflows/unit_tests.yaml
.gitignore
.gitmodules
.vscode/launch.json
.vscode/settings.json
README.md
flutterw
lib/main.dart
pubspec.lock
pubspec.yaml
scripts/android_integration_test.sh
scripts/install_flutter.sh
scripts/ios_integration_test.sh

Tasks:
- -----------------------------------------------------------------------------
settings.json file
```json
{
"dart.flutterSdkPath": ".flutter",
"dart.lineLength": 120,
"git.ignoreLimitWarning": true,
"explorer.autoReveal": false,
}
```
this is for integration `vs code` and `flutter_wrapper`
```json
{
"dart.flutterSdkPath": ".flutter",
}
```
- -----------------------------------------------------------------------------
I thought github workflow and our scripts it is correct but check please.

Flutter wrapper

---

analysis_options.yaml
lib/common/components/address_input_field.dart
lib/mocks/storage/mock_local_storage.dart
lib/page/account/create/add_account_page.dart
lib/page/account/create/create_account_form.dart
lib/page/account/import/import_account_page.dart
lib/page/assets/index.dart
lib/page/profile/contacts/contact_page.dart
lib/service/encointer_feed/feed.dart
lib/service/substrate_api/account_api.dart
lib/service/substrate_api/api.dart
lib/service/substrate_api/assets_api.dart
lib/service/substrate_api/core/js_api.dart
lib/service/substrate_api/encointer/encointer_api.dart
lib/service/substrate_api/encointer/no_tee_api.dart
lib/service/tx/lib/src/submit_to_js.dart
lib/store/account/account.dart
lib/store/app.dart
lib/store/assets/assets.dart
lib/store/assets/types/balances_info.dart
lib/store/encointer/encointer.dart
lib/store/encointer/encointer.g.dart
lib/store/settings.dart
lib/utils/format.dart
lib/utils/local_storage.dart
test_driver/real_app.dart

fix invalid assignments

---

.vscode/launch.json
ios/Podfile.lock
lib/main.dart
lib/page-encointer/bazaar/3_businesses/business_detail.dart
lib/page-encointer/bazaar/menu/2_my_businesses/businesses_on_map.dart
lib/page-encointer/common/encointer_map.dart
lib/service/notification.dart
pubspec.lock
pubspec.yaml

Pub Updated `flutter pub updated`

run: flutter pub updated

---

ios/Runner/Info.plist
lib/page-encointer/ceremony_box/components/ceremony_register_button.dart

Update CFBundleLocalizations in Info.plist [see more](https://docs.flutter.dev/development/accessibility-and-localization/internationalization)
Fixed ui error added `FittedBox`

Update CFBundleLocalizations for IOS and fix ui error

---

README.md
lib/js_service_encointer/README.md
lib/js_service_encointer/src/service/encointer.js
lib/js_service_encointer/test/cantillon.test-e2e.js
lib/js_service_encointer/test/service/account.test.js
lib/js_service_encointer/test/service/encointer.test.js
lib/js_service_encointer/test/service/scale-codec.test.js
lib/js_service_encointer/test/service/substratee.test.js
lib/js_service_encointer/test/testUtils/networks.js

I added a bit of documentation because I think you will also have to understand this a bit better, as it will help you even with unrelated tasks. @Eldar2021, @SourbaevaJanaraJ 
So please comment on things that are not clear here.

Add documentation about how the JS part interacts with dart.

---

lib/page/network_select_page.dart

When I change network I gave a error
```console
I/flutter ( 4840): No observables detected in the build method of Observer
I/flutter ( 4840): Observer constructed from: _NetworkSelectPageState.build
```

fix `Observer` error network_select_page

---

.vscode/launch.json
lib/store/assets/types/balances_info.dart

Fixed BalancesInfo class error
there were two classes, but in fact we use only one class cause one of them is private and we don't use it anywhere. so i decided to delete useless private class, I think it is right decision. what do you think?

Fix BalancesInfo class error

---

lib/js_service_encointer/src/service/encointer.js

* Closes https://github.com/encointer/encointer-wallet-flutter/issues/903#issuecomment-1351063284

fix negative degree issue in meetup time

---

pubspec.lock
pubspec.yaml

Upgrade pub dependencies

---

.github/workflows/unit_tests.yml

The previous test did not what I expected it to do: it checked if the files changed relative to master.

[GA] fix the test for the file diff

---

.github/workflows/android_integration_test.yml
.github/workflows/ios_integration_test.yml
.github/workflows/js_ci.yml
scripts/android_integration_test.sh
scripts/ios_integration_test.sh
scripts/run_encointer_node_notee_docker.sh

Finally, our test coverage in the CI has increased a lot! 🥳 
Thanks a lot @mosonyi for creating the docker images!

run encointer node docker container in CI and enable all integration tests

---

analysis_options.yaml
lib/page/qr_scan/qr_codes/contact.dart
lib/page/qr_scan/qr_codes/invoice.dart
lib/page/qr_scan/qr_codes/qr_code_base.dart
lib/page/qr_scan/qr_codes/voucher.dart
test/page/qr-scanner/qr_codes/contact_test.dart
test/page/qr-scanner/qr_codes/invoice_test.dart

fix overridden_fields

---

lib/service/notification/lib/src/ceremony_notifications.dart

The reworked the IDs such that they make sense intuitively, and tried to make the ID handling as dart-ergonomic as possible. :)

[ceremonyNotifications] change notification offsets and include one more category

---

ios/Runner.xcodeproj/project.pbxproj
lib/common/components/address_input_field.dart
lib/page/assets/transfer/transfer_page.dart
lib/page/profile/account/account_manage_page.dart
lib/service/tx/lib/src/submit_tx_wrappers.dart
test_driver/helpers/other_test.dart
test_driver/helpers/real_app_helper.dart
test_driver/real_app_test.dart

Created new account by name "Tom". Registered accounts Alice, Tom, Bob, Charlie, and start meetup. After meetup Alice erdorses to Sezar (test: reputable endorses newbie from Bootstraper account). Tom endorses to Li  (test: reputable endorses newbie from Reputable  account).

Add integration test: reputable endorses newbie 

---

lib/models/index.dart
lib/models/transfer/transfer_history.dart
lib/models/transfer/transfer_history.g.dart
lib/modules/modules.dart
lib/modules/settings/view/lang_page.dart
lib/modules/transfer/logic/transfer_gistory_store.dart
lib/modules/transfer/logic/transfer_gistory_store.g.dart
lib/modules/transfer/transfer.dart
lib/modules/transfer/view/transfer_history_view.dart
lib/modules/transfer/widgets/transaction_card.dart
lib/page/assets/transfer/transfer_page.dart
lib/router/app_router.dart
lib/utils/translations/translations_home.dart

Added Transfer history page only UI
Please Let me know if you have any suggestions.
And of course check the words and phrases shown in the ui

Placeholder page for transfer history

---

README.md
ios/Podfile.lock
pubspec.lock
pubspec.yaml
test_driver/real_app_test.dart

@SourbaevaJanaraJ  and I had a few conflicts with our flutter versions and I had trouble with her computer. So I decided to make a PR to upgrade the flutter version. I tested it and there were no issues.

Bump flutter v3.7.1

---

.github/workflows/android_build.yml
.github/workflows/unit_tests.yml
README.md
ios/Podfile.lock
lib/utils/translations/translations_profile.dart
melos.yaml
packages/ew_format/README.md
packages/ew_models/README.md
pubspec.lock
pubspec.yaml

I seemed to have found a little trick to circumvent the `pub-cache` issue. 
Works: https://github.com/encointer/encointer-wallet-flutter/actions/runs/4118158030

Melos cache fixes and fixes for windows.

---

analysis_options.yaml
flutterw
lib/page-encointer/bazaar/menu/camera/image_picker_scaffold.dart
lib/page-encointer/ceremony_box/ceremony_box.dart
lib/page/assets/transfer/payment_confirmation_page/index.dart
lib/page/qr_scan/qr_scan_service.dart
lib/service/deep_link/deep_link.dart
lib/service/tx/lib/src/submit_to_js.dart
lib/store/encointer/encointer.dart

enable more lint
` no_default_cases: true`

enabled more lint

---

app/lib/page/assets/transfer/transfer_page.dart
app/lib/page/qr_scan/qr_scan_service.dart
app/lib/router/app_router.dart
app/lib/service/deep_link/deep_link.dart

In general this PR was made to solve this #1026 problem. 
Fixed some noticeable codes.

Fix broken invoice link: handle missing fields

---

docker/wallet/.well-known/assetlinks.json
docker/wallet/Dockerfile
docker/wallet/README.md

Add assetlinks.json #1031

---

app/lib/modules/account/view/add_account_view.dart
app/lib/modules/account/view/import_account_view.dart

Try fix account creation texts
* Closes #1060

Fix account creation texts

---

app/lib/page/assets/transfer/payment_confirmation_page/index.dart
app/lib/service/notification/lib/src/notification_plugin.dart
app/lib/service/substrate_api/account_api.dart
app/lib/service/tx/lib/src/params.dart
app/lib/service/tx/lib/src/submit_to_js.dart
app/lib/service/tx/lib/src/submit_tx_wrappers.dart
app/lib/store/account/account.dart
app/lib/utils/translations/translations_encointer.dart
app/lib/utils/translations/translations_home.dart

* Closes #786 
I have thought a lot to complete this task, but I believe this is the best and easiest way to do it. If there is a better way, please let me know 🥺.
Please check the translations :)
* Title:
* English: Endorse newcomer
* German: Neuling unterstützen
* French: Approuver un nouveau venu
* Russian: Одобрить нового участника
* Body: 
* English: Thank you for endorsing the newcomer to our community!
* German: Danke, dass Sie den Neuling in unserer Gemeinschaft unterstützt haben!
* French: Merci d'approuver le nouveau venu dans notre communauté!
* Russian: Благодарим за одобрение нового участника в нашем сообществе!
* Title:
* English: You have successfully registered for the meetup!
* German: Sie haben sich erfolgreich für das Treffen registriert!
* French: Vous vous êtes …

Localized translations for transaction results

---

app/ios/Podfile.lock

Regenerate Podfile.lock with cocoapod v1.12.0
* Closes #1097

Regenerate Podfile.lock with cocoapod v1.12.0

---

app/lib/models/ceremonies/ceremonies.dart
app/lib/models/ceremonies/ceremonies.g.dart
app/lib/service/substrate_api/encointer/encointer_api.dart
app/lib/service/tx/lib/src/submit_tx_wrappers.dart
melos.yaml

make `AggregatedAccountData.global` non-nullable because it can't be null.
* Closes #1091

AggregatedAccountData.global non-nullable

---

app/lib/modules/settings/logic/app_settings_store.dart
app/lib/modules/settings/logic/app_settings_store.g.dart
app/lib/page-encointer/ceremony_box/ceremony_box.dart
app/lib/page-encointer/ceremony_box/ceremony_info.dart
app/lib/page-encointer/ceremony_box/components/ceremony_info_and_calendar.dart
app/lib/page-encointer/meetup/ceremony_step2_scan2.dart
app/lib/page/assets/index.dart
app/lib/page/assets/transfer/transfer_page.dart
app/lib/page/profile/account/account_manage_page.dart
app/lib/page/profile/contacts/contact_page.dart
app/lib/page/profile/index.dart
app/lib/page/qr_scan/qr_scan_page.dart
app/lib/store/settings.dart
app/lib/store/settings.g.dart

First step for the refactoring of the integration tests, see #1129.
* Closes #1118

Transfer `developerMode` to `AppSetting` store

---

app/lib/common/components/logo/participant_avatar.dart
app/lib/page-encointer/meetup/ceremony_step2_scan2.dart
app/lib/utils/extensions/layout/layout_extensions.dart

Made  dynamic the size of animals as overlay on the QR code, on the phones with small screens animals will be smaller.
Closes #1143

Cycle gathering QR scan fails because animal is too big on small screens 

---

app/lib/main.dart
app/lib/modules/settings/logic/app_settings_store.dart
app/lib/modules/settings/logic/app_settings_store.g.dart
app/lib/modules/settings/service/lang_service.dart
app/lib/modules/settings/view/lang_page.dart
app/lib/page/profile/index.dart
app/test_driver/helpers/command/real_app_command.dart
app/test_driver/helpers/command/real_app_functions.dart
app/test_driver/helpers/screenshots.dart
app/test_driver/real_app.dart
app/test_driver/real_app_test.dart

* Closes #1119.
I did a slight refactoring of the app-settings regarding setting the locale, and added a method to change the language from the integration tests directly without going to the profile page. Added two integration tests that change the language, one via the profile page and one via a flutter driver command directly.
Test-screenshot: [screenshots](https://github.com/Eldar2021/eldar2021.github.io/blob/main/images/test-de.png). Looks good. :)

Change language in integration test

---

app/lib/page/assets/index.dart

Re-introduce the layout fix from #1251 that was lost in a rebase #1238.

[assets-page] fix button layout that was accidentally unfixed

---

app/lib/modules/transfer/widgets/transaction_card.dart

Changed tx history icon color
Closes #1317

tx history: icons should be the same colour as the numbers

---

app/lib/page-encointer/ceremony_box/components/ceremony_progress_bar.dart

Changed SizedBox to DecoratedBox.
Closes #1288

Fix Ceremony Cycle Progress Bar

---

app/lib/page/qr_scan/qr_scan_page.dart
app/lib/page/qr_scan/qr_scan_service.dart
app/pubspec.lock
app/pubspec.yaml

I searched a lot for the cause of the error. :) But I never thought it was an error from the package. 😃 
https://github.com/juliansteenbakker/mobile_scanner/pull/594
* Closes #1334

fix scanning invoice qr code from `TransferPage`

---

app/lib/mocks/mock_bazaar_data.dart
app/lib/models/bazaar/offering_data.dart
app/lib/models/bazaar/offering_data.g.dart
app/lib/page-encointer/new_bazaar/businesses/logic/business_utils.dart
app/lib/page-encointer/new_bazaar/businesses/view/businesses_view.dart
app/lib/page-encointer/new_bazaar/businesses/widgets/businesses_card.dart
app/lib/page-encointer/new_bazaar/single_business/views/single_business_view.dart
app/lib/page-encointer/new_bazaar/single_business/widgets/single_business_detail.dart
app/test/mock/api/mock_encointer_api.dart
app/test/mock/data/mock_encointer_data.dart
app/test/store/bazaar/single_business_view_store_test.dart

Unit test for single business back end

Test for a single business page back end

---

app/lib/page-encointer/meetup/ceremony_step2_scan2.dart
app/lib/page-encointer/meetup/scan_claim_qr_code.dart

I searched but couldn't find the exact cause of the error.
The application asks for camera permission. 
If it gives permission, the scan is done.
If not, an error dialog pops up with two buttons
1) Open app setting
2) Back previously page.
But I can say with high probability that this could be the mistake.
```dart
controller: MobileScannerController(detectionTimeoutMs: 1250),
```
If you remember there was the same scan problem with `TransferPage`. And it was solved with this.
* Closes #1310

Try fix gathering scanner bug

---

app/lib/l10n/arb/app_de.arb
app/lib/l10n/arb/app_fr.arb
app/lib/page/assets/index.dart

Shorten & center text of claim pending income button

---

app/lib/common/components/gradient_elements.dart
app/lib/common/components/map/encointer_map.dart
app/lib/l10n/arb/app_de.arb
app/lib/l10n/arb/app_fr.arb
app/lib/models/transfer/transfer_history.dart
app/lib/modules/account/view/create_account_view.dart
app/lib/modules/meetup_location/view/meetup_location_view.dart
app/lib/modules/transfer/logic/transfer_history_view_store.dart
app/lib/modules/transfer/widgets/transaction_card.dart
app/lib/modules/transfer/widgets/transactions_list.dart
app/lib/page-encointer/meetup/ceremony_step1_count.dart
app/lib/page-encointer/meetup/ceremony_step2_scan2.dart
app/lib/page-encointer/meetup/scan_claim_qr_code.dart
app/lib/page/assets/index.dart
app/lib/page/profile/account/export_result_page.dart
app/pubspec.yaml

1) screenshots with master branch [screenshots01.zip](https://github.com/encointer/encointer-wallet-flutter/files/12101674/screenshots01.zip)
2) screenshots with `js/textstyles inside text theme` branch [screenshots.zip](https://github.com/encointer/encointer-wallet-flutter/files/12101682/screenshots.zip)

Fixed some text styles

---

app/lib/common/components/address_input_field.dart
app/lib/modules/transfer/widgets/transactions_list.dart
app/lib/page/profile/contacts/contact_list_page.dart
app/lib/page/qr_scan/qr_scan_service.dart
app/lib/store/settings.dart
app/lib/store/settings.g.dart

Other change:
* removed `settings.contactListAll` in favoring almost the same `settings.knownAccounts`. Closes #1372
* Resolves the contact syncing issue described in https://github.com/encointer/encointer-wallet-flutter/issues/1402

Fix displaying contacts in `AddressInputField`

---

app/lib/l10n/arb/app_de.arb
app/lib/l10n/arb/app_en.arb
app/lib/l10n/arb/app_fr.arb
app/lib/l10n/arb/app_ru.arb
app/lib/page/assets/receive/receive_page.dart

Ensure the whole QR-code is displayed on receive page

---

app/lib/common/components/form/scrollable_form.dart
app/lib/page/assets/transfer/transfer_page.dart
app/test_driver/app/voucher/voucher_integration_test.dart

TransferPage: avoid opening qr-scanner when clicking on the empty spaces next to the scanner icon

---

app/lib/page/assets/announcement/view/announcement_view.dart
app/lib/page/assets/index.dart

Finally, the cause of this problem was found. The bug has been fixed and a code fix has been made.
* Closes #1286

Fix: balance can't be fetched after changing account

---

.github/workflows/android_build.yml
.github/workflows/android_integration_test.yml
.github/workflows/ios_integration_test.yml
.github/workflows/js_ci.yml
scripts/fdroid_init.sh
scripts/install_node.sh

bump node in CI and install scripts to 18.14.2

---

app/lib/page-encointer/ceremony_box/components/unregister_link_button.dart
app/lib/utils/alerts/app_alert.dart

[UnregisterParticipant] fix potential dialog popping error while unregistering

---

app/lib/modules/meetup_location/view/meetup_location_view.dart

[meetup_location_view] remove location index from app bar

---

app/lib/common/components/map/encointer_map.dart

avoid using subdomains for openstreetmap server

---

app/js_service_encointer/README.md
app/js_service_encointer/src/service/encointer.js
app/js_service_encointer/test/service/encointer.test.js
app/lib/service/substrate_api/encointer/encointer_api.dart
app/pubspec.lock
app/pubspec.yaml
app/pubspec_overrides.yaml
packages/ew_keyring/pubspec.lock
packages/ew_keyring/pubspec.yaml
packages/ew_keyring/pubspec_overrides.yaml
packages/ew_keyring/test/address_utils_test.dart
packages/ew_polkadart/lib/ew_polkadart.dart
packages/ew_polkadart/pubspec.lock
packages/ew_polkadart/pubspec.yaml

* Use dart for `getBootstrapper`. Closes #1541.
* Use dart for newbie tickets, part of #1561

use dart for `getBootstapper`, `remainingNewbieTicketsPerReputable` and `remainingNewbieTicketsPerBootstrapper`

---

app/js_service_encointer/src/service/encointer.js
app/lib/service/substrate_api/encointer/encointer_api.dart
app/pubspec.lock
app/pubspec.yaml
app/pubspec_overrides.yaml
packages/ew_encointer_utils/lib/src/assigment.dart
packages/ew_encointer_utils/test/assignment_test.dart

use dart in `getNextMeetupTime`

---

app/lib/service/substrate_api/assets_api.dart

In the change to the dart getter API, we used the wrong storage value to query the balances as we use the systen pallet, and not the balances pallet. Closes #1582.

[assetsApi] fix native balance getter

---

app/lib/page/profile/contacts/contact_detail_page.dart

[contact_detail_page] prevent red screen in case no community is chosen

---

.github/workflows/android_build.yml
.github/workflows/android_integration_test.yml
.github/workflows/fdroid.yml
.github/workflows/ios_integration_test.yml
.github/workflows/unit_tests.yml

fixes warnings about node-v16 deprecation

[CI] bump workflow actions to use node-v20 runtime

---

app/lib/page/profile/account/account_manage_page.dart

Only show faucets where:
* the user has reputation for the faucet's whitelist
* the currently chosen community is in the whitelist
Closes #1497

Only show relevant faucets

---

app/lib/common/components/logo/community_icon.dart
app/lib/page-encointer/common/community_chooser_panel.dart
app/lib/page-encointer/meetup/ceremony_step3_finish.dart
app/lib/page/assets/announcement/widgets/announcement_card.dart
app/lib/page/profile/account/account_manage_page.dart
app/lib/store/encointer/encointer.dart
app/lib/store/encointer/encointer.g.dart
app/lib/store/encointer/sub_stores/community_store/community_store.dart
app/lib/store/encointer/sub_stores/community_store/community_store.g.dart

[AccountManagePage] display correct community icon for non-current community and hide 0 balances

---

app/lib/service/tx/lib/src/submit_tx_wrappers.dart

get encointer balance after sending an encointer balance transfer

---

.github/workflows/ios_integration_test.yml

Doing this because this is the new app store release requirement.

[CI] bump xcode to v15.2 in CI

---

app/pubspec.lock
app/pubspec.yaml
app/pubspec_overrides.yaml
packages/ew_encointer_utils/pubspec.lock
packages/ew_encointer_utils/pubspec.yaml
packages/ew_encointer_utils/pubspec_overrides.yaml
packages/ew_keyring/pubspec.lock
packages/ew_keyring/pubspec.yaml
packages/ew_keyring/pubspec_overrides.yaml
packages/ew_polkadart/lib/generated/encointer_kusama/encointer_kusama.dart
packages/ew_polkadart/pubspec.lock
packages/ew_polkadart/pubspec.yaml
packages/ew_polkadart/pubspec_overrides.yaml
packages/ew_primitives/pubspec.lock
packages/ew_primitives/pubspec.yaml
packages/ew_primitives/pubspec_overrides.yaml

This is mandatory to make transaction make work on mainnet again

support `CheckMetadata` signed extensions

---

app/lib/store/settings.dart
app/lib/store/settings.g.dart

Have found this one while investigating missing tasks for #1683.

[store/settings] remove unused `changeLang` method

---

app/lib/page-encointer/democracy/democracy_page.dart
app/lib/page-encointer/democracy/widgets/proposal_tile.dart

Closes #1680
Checked on the smallest emulator possible, seems fixed, see [image](https://github.com/user-attachments/assets/e8d81fb7-64fc-46ff-8aaf-51d749ed738c)

[Democracy] fix clipped proposal id on small phones

---

app/lib/page-encointer/democracy/democracy_page.dart

created a landing post on the forum where people will be directed to categories for proposals
https://forum.encointer.org/t/deliberation-for-encointer-democracy-proposals/126
statically linking form democracy page

add proper link to forum for deliberation of democracy proposals

---

app/lib/l10n/arb/app_de.arb
app/lib/l10n/arb/app_en.arb
app/lib/l10n/arb/app_fr.arb
app/lib/l10n/arb/app_ru.arb
app/lib/l10n/arb/app_sw.arb
app/lib/modules/account/view/add_account_view.dart
app/lib/modules/account/view/import_account_view.dart
app/lib/modules/login/logic/login_store.dart
app/lib/modules/login/view/login_dialog.dart
app/lib/page/assets/transfer/payment_confirmation_page/index.dart
app/lib/page/profile/account/account_manage_page.dart
app/lib/page/profile/index.dart
app/lib/service/tx/lib/src/submit_tx_wrappers.dart
app/test_driver/app/profile/profile_test.dart
app/test_driver/app_test.dart

Improve code in LoginDialog. This was done while investigating #1706, but I couldn't find the cause yet for the bug, nor could I reproduce it locally (didn't try reproducing that hard though).
Checked locally that the integration tests worked

Simplify `LoginDialog` code

---

app/lib/page-encointer/democracy/helpers.dart

Fix: democracy -  wrong status display

---

app/android/app/build.gradle
app/android/build.gradle
app/android/gradle/wrapper/gradle-wrapper.properties
app/android/settings.gradle
app/pubspec.lock
packages/ew_http/pubspec.lock
packages/ew_http/pubspec.yaml
packages/ew_storage/pubspec.lock
pubspec.lock
pubspec.yaml

Whilst doing this, I migrated the gradle settings to the declarative format. Closes https://github.com/encointer/encointer-wallet-flutter/issues/1723.
Tests:
* Local integration tests worked
* IOS build in appcenter worked

bump to flutter 3.19.0 and upgrade gradle/kotlin

---

app/lib/common/components/address_input_field.dart
app/pubspec.lock
app/pubspec.yaml

There were some small breaking changes in the lib, so I wanted to update it separately, rather than together with the rest.

bump dropdown_search to v6

---

app/lib/page-encointer/democracy/widgets/proposal_tile.dart
app/lib/store/encointer/encointer.dart
app/lib/store/encointer/encointer.g.dart

fix proposal enactment date: should be next assigning phases' state

---

app/lib/page-encointer/democracy/proposal_page/propose_page.dart

* Closes #1778 
* Closes #1776

Fix: Apply decimals for issueSwapNativeProposal and repution needs to be for the prosposals community if local.

---

app/lib/l10n/arb/app_de.arb
app/lib/l10n/arb/app_en.arb
app/lib/l10n/arb/app_fr.arb
app/lib/l10n/arb/app_ru.arb
app/lib/l10n/arb/app_sw.arb
app/lib/page-encointer/democracy/widgets/proposal_tile.dart

* Closes https://github.com/encointer/encointer-wallet-flutter/issues/1772
* Closes https://github.com/encointer/encointer-wallet-flutter/issues/1769
This is how it looks like now: ![image](https://github.com/user-attachments/assets/19add909-40d8-4237-8671-9ba31a85d6e8)

[Democracy] proposal description updates after a proposal passes proposalLifetime or confirmingPeriod

---

app/lib/page-encointer/democracy/helpers.dart
app/lib/page-encointer/democracy/widgets/proposal_tile.dart
app/test/page_encointer/democracy/proposal_page/helpers.dart

Fix condition for checking turnout bias

---

.github/workflows/unit_tests.yml
app/android/app/build.gradle
app/android/build.gradle
app/ios/Flutter/AppFrameworkInfo.plist
app/ios/Podfile.lock
app/l10n.yaml
app/lib/gen/assets.gen.dart
app/lib/modules/settings/view/lang_page.dart
app/lib/page-encointer/democracy/proposal_page/propose_page.dart
app/lib/page/reap_voucher/reap_voucher_page.dart
app/lib/service/substrate_api/api.dart
app/lib/service/substrate_api/core/reconnecting_ws_provider.dart
app/lib/service/substrate_api/encointer/encointer_api.dart
app/pubspec.yaml
flutterw
packages/endpoint_manager/pubspec.yaml
packages/ew_encointer_utils/pubspec.yaml
packages/ew_format/pubspec.yaml
packages/ew_http/pubspec.yaml
packages/ew_keyring/pubspec.yaml
packages/ew_polkadart/pubspec.yaml
packages/ew_primitives/pubspec.yaml
packages/ew_storage/pubspec.yaml
packages/ew_substrate_fixed/pubspec.yaml
packages/ew_test_keys/pubspec.yaml
pubspec.lock
pubspec.yaml

As the last time it went quite smoothly and we have a stable CI finally, I felt ready to update to the most recent flutter too now.
* Split unit tests into separate jobs for a better overview and more independence of jobs
* #1822
* #1819

bump flutter 3.35
