encointer/encointer-wallet-flutter

- lib/js_service_encointer/src/service/encointer.js
- lib/store/settings.dart
- lib/utils/format.dart
- pubspec.lock
- pubspec.yaml
- test/utils/format_test.dart
* Change default network: To Encointer Testnet Gesell. Closes #43. Note you can clear the App cache with: adb shell pm clear org.encointer.wallet
* Display currency identifier as base58. I chose to handle the Cid in the background still as hex. Only the formatting method was adjusted. Closes #19
> Ux refinements

- lib/page-encointer/meetup/MeetupPage.dart
- lib/page-encointer/meetup/attestation/attestationCard.dart
- lib/page-encointer/meetup/attestation/components/stateMachinePartyA.dart
- lib/page-encointer/meetup/attestation/components/stateMachinePartyB.dart
- lib/page/assets/index.dart
MeetupPage: Remove hardcoded password. Show PasswordInputDialog at the start of the meetup (after amount of attendees has been confirmed) and cache it for the time of the meetup. Fixes: #68 
Tested with a successful meetup.
> Remove hardcode password in meetup

- lib/service/substrateApi/api.dart
Was due to erroneous String comparison, which gave repeated == true if the call to be dispatched contained a substring of the already registered call in the msgCompleter.
e.g. repeated == true for `account.gen` if `account.genIcons` has been registered before.
This is the underlying issue of #90. Fixes #90
> Fix bug: False positive repeated JS calls.

- lib/page-encointer/phases/registering/registerParticipantPanel.dart
After discussing the unregister button which does nothing in the background, it was decided to remove it. 
I thought maybe just leaving a card with the info that the participant is registered. 
Thoughts?
closes #207
> Replace unregister button by "participant registered" card

- lib/config/consts.dart
- lib/js_service_encointer/src/index.js
- lib/js_service_encointer/src/service/scale-codec.js
- lib/js_service_encointer/test/service/scale-codec.test.js
- lib/mocks/api/api.dart
- lib/page-encointer/meetup/claimQrCode.dart
- lib/page-encointer/meetup/scanClaimQrCode.dart
- lib/page-encointer/meetup/startMeetup.dart
- lib/service/substrateApi/api.dart
- lib/service/substrateApi/codecApi.dart
- lib/utils/i18n/encointer.dart
* Reduces the claim data size by about 50%. Closes #183.
* Also closes #189. We wait 3 seconds when we scanned the claim. If the JS-decoding has not returned by then, we assume it has failed. I think this is enough time, on my cellphone it takes less than 500ms.
> Show ClaimQR-code as scale-encoded hex-string

- lib/js_service_encointer/test/cantillon.test-e2e.js
- lib/js_service_encointer/test/gesell.test-e2e.js
- lib/js_service_encointer/test/service/account.test.js
- lib/js_service_encointer/test/service/encointer.test.js
- lib/js_service_encointer/test/service/substratee.test.js
As of jest > 27 the `jest.setTimout` method does not seem to work correctly: https://github.com/facebook/jest/issues/11500. This leads to a timeout error-rate of 30% in the CI.
This workaround should solve this and thereby fix the flaky gesell-integration test.
Edit: Seems to do the trick. I run the tests about 10 times, and it did not fail once.
> Fix flaky gesell integration test: `sendFaucetTx method`

- lib/common/components/passwordInputDialog.dart
There was a bug; if a wrong PIN was entered in the passwordDialog, nothing happened.
> [passwordInputDialog] fix show error message on wrong pin

- lib/common/components/editIcon.dart
- lib/js_service_encointer/test/gesell.test-e2e.js
- lib/page/account/create/addAccountPage.dart
- lib/page/account/create/createPinPage.dart
- lib/page/account/import/importAccountForm.dart
- lib/page/account/import/importAccountPage.dart
- lib/page/assets/transfer/transferPage.dart
- lib/page/networkSelectPage.dart
- lib/page/profile/account/accountManagePage.dart
- lib/page/profile/index.dart
- lib/service/substrateApi/api.dart
- lib/service/substrateApi/apiAccount.dart
- lib/store/app.dart
- lib/store/assets/assets.dart
* Closes #357 
The reason for #357 was that the loading of account-specific data was not awaited before making `webApi` calls. This lead to webApi calls with wrong/outdated arguments.
Changes in this PR:
* unify redundant definitions of `_loadAccountCache` in `appStore.loadAccountCache`
* introduce `webApi.fetchAccountData()` which fetches all account-specific data.
* always await loading of cache to prevent potential bad states while making webApi calls.
> Fix cache loading after account switch

- lib/service/substrateApi/api.dart
- lib/service/substrateApi/encointer/apiEncointer.dart
- lib/utils/translations/translationsEncointer.dart
* Quite positive that this closes #374. I am not 100% certain though because I couldn't reproduce the bug before. Below is my guess to why this solves the issue:
I remember seeing the following error in the logs without being able to identify what it could cause:
```
unable to create type `MeetupIndexType` with negative number
```
I deemed it to be not relevant because it was in the registering phase. However, the default case was that a failing JS-call without proper error handling, will make subsequent calls to the same JS-method noop's because dart was still waiting for the responsible message completer to return (See #387). I guess a failing `encointer.getMeetupRegistry` call prevented the `meetupRegistry` from being updated, causing the above issue.
Changes in this PR:
* default …
> Fix invalid meetup registry in store

- lib/page/account/import/importAccountPage.dart
Before, there was always a cryptic error message of `sr25519` key type not being supported, when something with an account import failed. This is not only cryptic, but also most of the time wrong.
Here we introduce the change that the JS-returned error is not simply swallowed but transparently displayed in that `CupertinoAlertDialog`.
> Better error for invalid mnemonic

- ios/Podfile
* Closes #241 
Not 100% sure that this solves the issue. There is very little information, but I guess that the appstore reports this because one of our dependencies needs that permission even though we don't use it.
I suggest we try this approach. If it does not work, we add the usage string here: https://github.com/encointer/encointer-wallet-flutter/blob/0a513055a5d996eccc8943e1d99e7be963a9a672/ios/Runner/Info.plist#L41
> Fix apple appstore privacy issues

- lib/page-encointer/phases/attesting/attestingPage.dart
- lib/utils/translations/translationsEncointer.dart
* Closes #431 
Changes:
* add button `Purge previously scanned claims` on attesting phase view
* minimaly update the design by using our new design templated widgets.
* change deprecated texts: attestations -> claims
> Allow Purging of scanned claims

- lib/js_service_encointer/src/service/encointer.js
- lib/page-encointer/common/assignmentPanel.dart
- lib/page-encointer/encointerEntry.dart
- lib/page-encointer/phases/assigning/assigningPage.dart
- lib/page-encointer/phases/attesting/attestingPage.dart
- lib/service/substrateApi/encointer/apiEncointer.dart
- lib/store/encointer/encointer.dart
- lib/store/encointer/encointer.g.dart
* Closes #454 
* Closes #456 
* Closes #457
Changes:
* If the user is not assigned to a meetup, the meetup time is computed based on the community's first location.
* Fetch and cache all meetup locations of communities
* Introduce computed value `isRegistered`.
> Fix endless activity indicator on assignment panel

- lib/page-encointer/homePage.dart
* the user has to tap on the icons in the bottom navigation bar now and cannot swipe between tabs. Closes #420
> bugfix bottom navigation bar, swiping is now disabled

- lib/js_service_encointer/test/gesell.test-e2e.js
Needed to be fixed due to updated weights. As we will continue to have changing weights now, I changed the test to not check against a specific number.
> [JS] fix gesell integration tests

- lib/page-encointer/common/communityChooserPanel.dart
- lib/page/account/create/addAccountPage.dart
- lib/page/assets/account_or_community/AccountOrCommunityData.dart
- lib/page/assets/account_or_community/accountOrCommunityItemHorizontal.dart
- lib/page/assets/account_or_community/switchAccountOrCommunity.dart
- lib/page/assets/index.dart
- lib/page/assets/transfer/transferPage.dart
- lib/page/profile/index.dart
- lib/utils/translations/translationsProfile.dart
* Add a combined community/account selector
* No longer show mock data but show the actual available accounts in the sliding up panel
* Add community opens the world map with pins with communities, so you can select a community there
* Add account opens the existing add account page
* The selected account/community gets highlighted with a blue circle
* clicking outside the panel closes it (this is the only way to close it)
* closes #331 and remainder of #327
> Add combined account community selector and fix remaining issues from #327

- lib/page/account/create/addAccountForm.dart
- lib/page/account/create/addAccountPage.dart
- lib/page/profile/index.dart
As we can arrive to that page from multiple paths, it is a potential error source that the `addAccountPage` does not check itself if the PIN has already been entered. See https://github.com/encointer/encointer-wallet-flutter/pull/502#pullrequestreview-922087463.
Here, we change the paradigm such that the page checks itself upon initialization if it needs to ask for the PIN.
This also removed the weird UX that we need to press twice on the `addAccount` button on the profile page.
> addAccountPage checks itself if the PIN needs to be entered

- lib/page-encointer/common/assignmentPanel.dart
* Closes #412
Note: I have not thoroughly tested it. But as @brenzi said that it only seemed to be a 12 vs 24 hours format issue, the issue should be solved as the timestamp given in https://github.com/encointer/encointer-wallet-flutter/issues/412#issuecomment-1080376435 is displayed as `2022-03-28-13:08` now.
> [assignmentPanel] fix: show meetup time in 24 hour format

- lib/page-encointer/common/communityChooserOnMap.dart
- lib/page-encointer/common/encointerMap.dart
- lib/page/account/create/createAccountForm.dart
- lib/page/account/create/createPinForm.dart
- lib/page/account/create/createPinPage.dart
- lib/page/account/import/importAccountPage.dart
- lib/utils/translations/translationsEncointer.dart
The constructor of `CommunityChooserOnMap` does simply return when no communities are in the store. This was very unintuitive to debug in the onboarding process, as we seemed to skip the map. This PR introduces confirmation dialogue before proceeding to the homepage.
Other fixes:
- Closes #371 
- Closes #380. By fixing [#371](#371), we can now properly await the future of the account creation, so we will not proceed before it's finished.
- Resolve subtask of #330
> Gracefully handle no communities in onboarding.

- lib/js_service_encointer/src/service/scale-codec.js
- lib/page-encointer/common/assignmentPanel.dart
- lib/page-encointer/homePage.dart
- lib/page-encointer/meetup/scanClaimQrCode.dart
- lib/service/substrate_api/codecApi.dart
* Closes #516
UX-changes:
* Show a `CupertinoActivityIndicator()` overlay while decoding.
* Instead of a time-out, we catch the error in case there was one on the JS-side.
Todo:
> Improve meetup QR-Scanner UX

- lib/config/consts.dart
- lib/js_service_encointer/src/service/settings.js
Hardcode the SS58-prefix to 42 on the JS-side. This overwrites the SS58-prefix 2 for Kusama and Rococo.
* Closes #562 
* We should solve this properly in the future: See #567 
Tested that meetup registry contains the claimantPublic:
```
[EncointerApi]: AggregatedAccountData for sqm1v79dF6b and 5GrwvaE...: {
"global": {
"ceremonyPhase": "Attesting",
"ceremonyIndex": 2
},
"personal": {
"participantType": "Bootstrapper",
"meetupIndex": 1,
"meetupLocationIndex": 3,
"meetupTime": 1651142880000,
"meetupRegistry": ["5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y", "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty", "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"]
}
}
```
```
{
"path": "uid=5;encointer.signClaimOfAttendance",
"data": {
"claimantPublic": …
```
> [JS/settings]  hardcode SS58-prefix to 42.

- lib/page/profile/contacts/contactPage.dart
not deleted as observations may come handy when setting up "read only" point-of-sale devices
memo isn't used anywhere, but also here I only gated it behind developer mode
> hide observation checkbox and memo unless in developer mode

- lib/page-encointer/phases/registering/registerParticipantPanel.dart
- lib/page/assets/receive/receivePage.dart
- lib/page/assets/transfer/transferPage.dart
- lib/page/profile/contacts/contactDetailPage.dart
- lib/page/profile/contacts/contactPage.dart
- lib/page/profile/index.dart
- lib/page/qr_scan/qrScanPage.dart
a few minor things that bugged me for a while 
If a user wants to add a contact, but accidentally scans an invoice QR, that is now treated more intuitively by following the intention of the scanning user (not of the QRcode presenting user)
> minor but nice UX tweaks

- lib/page-encointer/encointerEntry.dart
- lib/page-encointer/homePage.dart
- lib/page-encointer/phases/assigning/assigningPage.dart
- lib/store/encointer/encointer.dart
fix the most annoying issues with the ceremony page:
* data now refreshes whenever ceremony page onFocus
* fix timeToMeetup calculation
* fix offline behaviour
Closes #605. However, as the app needs to work offline we still display possibly outdated content until refreshed
It would be better design to implement this refreshment in the store/api so we'd have an Observer we can use. However, I didn't want to intervene with the ceremonybox PR, so I consider this here temporary code that just fixes the issues. If the ceremony box solves this properly very soon, we don't need this PR
> Refresh ceremony data onfocus

- lib/js_service_encointer/src/service/encointer.js
- lib/page/assets/index.dart
- lib/service/substrate_api/encointer/encointerApi.dart
- lib/store/encointer/encointer.dart
- lib/utils/tx.dart
This introduces a poll in the callback to the ceremony phase subscription to make sure we get updated values from subsequent data fetches. See #632.
Before, we sometimes got outdated values for:
* ceremony index (reason for occasionally wrong ceremony indexes in claims, in fast-testing)
* aggregated account data
*  Reason for occasionally null meetup times in claims, n fast-testing
* Reason for showing participant as registered when transitioning from attesting -> registering.
With this change, I was able to test on rococo, without manually triggering state updates. (we just need to be a bit patient wait for ca. 9 seconds until the values are updated, this waiting time is currently not shown in the UX)
> Fix inconsistent data fetches upon ceremony phase transitions

- lib/common/components/encointerTextFormField.dart
- lib/page-encointer/meetup/ceremonyStep1Count.dart
- lib/page/account/create/addAccountForm.dart
- lib/page/account/create/createAccountForm.dart
- lib/page/account/import/importAccountForm.dart
- lib/page/assets/receive/receivePage.dart
- lib/page/assets/transfer/transferPage.dart
- lib/page/profile/account/accountManagePage.dart
- lib/page/profile/account/changePasswordPage.dart
- lib/utils/inputValidation.dart
- lib/utils/translations/translationsAccount.dart
* Closes #641
Changes:
* Disallow empty account name inputs whatsoever. Before we validated the input, and if it was empty, we used a default. Now the user is forced to actually enter a value.
* Fix: in in `createAccountForm` and `importAccountForm` the check to disallow empty inputs has been missing.
> Disallow null account name

- lib/page/account/create/createPinPage.dart
> Onboarding: automatically choose first community if there is only one.

- lib/page/profile/account/accountManagePage.dart
Tested:
* Shows old and new Leu community if the devMode is enabled
* Only shows the currently selected community if the devMode is disabled. (This might still be the old Leu!)
> [accountManagePage] only show current community overview if devMode is not enabled

- lib/config/consts.dart
- lib/mocks/data/mockMeetupOverrides.dart
- lib/models/encointer_feed/meetupOverrides.dart
- lib/models/encointer_feed/meetupOverrides.g.dart
- lib/models/index.dart
- lib/page-encointer/ceremony_box/ceremonyBox.dart
- lib/page-encointer/ceremony_box/components/ceremonyRegisterButton.dart
- lib/service/encointer_feed/feed.dart
- lib/service/substrate_api/encointer/encointerApi.dart
- lib/store/encointer/encointer.dart
- lib/store/encointer/encointer.g.dart
- lib/store/encointer/sub_stores/community_store/communityStore.dart
- lib/store/encointer/sub_stores/community_store/communityStore.g.dart
- test/models/encointer_feed/meetupOverrides_test.dart
- test/store/encointer/sub_stores/community_store/communityStore_test.dart
* Closes #656 
* Show hours and minutes in `RegisterParticipant` button, before it was only the day. I think this change makes sense outside the demo context too. [image](https://user-images.githubusercontent.com/37865735/175818240-1b053e19-59a7-4815-901e-3bce7a4afa8b.png)
* Shows first date of meetup overrides if Berlin or Buenos Aires test community is chosen.
* Did some tedious manual testing:
* Created meetup time overrides with two meetups for the `bootstrap_demo_community.py`
* Tested that demo community follows meetup time overrides, see below.
These tests were a bit tedious, I basically create some mock data such the `now()` is somewhere in between the meetup constellations, and then I played with the ceremony phases in the blockchain to see that everything works 
Registering:
* …
> Dynamic meetup overrides based on encointer feed

- lib/app.dart
- lib/page-encointer/meetup/ceremonyStep2Scan2.dart
- lib/page-encointer/meetup/scanClaimQrCode.dart
- lib/page/assets/receive/receivePage.dart
- lib/page/qr_scan/qrScanPage.dart
- lib/utils/UI.dart
- lib/utils/snackBar.dart
* Closes #664
I still lack the understanding why this suddenly became a problem, but I fixed it such that it should never occur again.
Instead of looking up the `ScaffoldMessenger` of in the `Scaffold` of a parent of the `context` we refer to the global instance of the `ScaffoldMessengerState` and use it in the newly introduced `RootSnackBar`. The documentation about this approach says:
* Global keys are, in general, more expensive than looking for the suitable instance in the widget's parent-tree.
* It is useful if one does navigate away from the current route while the snackbar is being displayed, therefore potentially removing the `Scaffold` from the widget tree, which will result in a failure of removing the snackbar after the timeout.
As we observed the latter before, I deemed this …
> Fix Qr-Code scanner freezing upon showing a snackBar

- lib/page-encointer/meetup/scanClaimQrCode.dart
- lib/page/qr_scan/qrScanPage.dart
depending on camera-observed background I found it hard to read the text in the QR scanner page. this makes it more readable. 
Also scanning performance showed to be better if the QR code doesn't fill the screen, so I narrowed the guiding frame. this also makes it more obvious for users that the scanner is different (better) now ;-)
> improve readability and narrow frame for qr code scanner

- lib/page-encointer/meetup/scan_claim_qr_code.dart
The back-button was barely visible. On iPhone, where you can't use the system back button this was confusing during the meetup procedure.
> fix ceremony-scanner-back-button

- lib/service/background_service/meetup/callback_dispatcher.dart
Fixes background execution for flutter > 3.1.5, according to https://github.com/fluttercommunity/flutter_workmanager#how-to-use-the-package
> [notifications] add dart-vm entry point which is needed for flutter > 3.1.5

- pubspec.lock
- pubspec.yaml
Deleted unused package [charts_flutter](https://pub.dev/packages/charts_flutter).
This package is very old and `DISCONTINUED`.
> deleted unused package charts_flutter

- .github/workflows/ios_integration_test.yaml
You can see the available runtimes with this command: https://github.com/encointer/encointer-wallet-flutter/blob/bd260ad6db6206793dc3adc1b697aecc2e68aebc/scripts/ios_init_env.sh#L10
We print the available runtimes in the CI in the prepare environment for IOS stage.
> [GA] update ios runtimes for ipad simulator creation

- .github/action-config.json
- scripts/install_flutter.sh
bump flutter to v3.3.5
Just change [.github/action-config.json](https://github.com/encointer/encointer-wallet-flutter/compare/bump-flutter-to-v3.3.5?expand=1#diff-15dfed428ba169dae5cff4d0596f570781351221c4eac61dea0f5343f77eaf69) and [scripts/install_flutter.sh](https://github.com/encointer/encointer-wallet-flutter/compare/bump-flutter-to-v3.3.5?expand=1#diff-50f077c0b529b9684d950c9fbfb0e88edc31152d07d8dbf57b0a29d0caf888e3)
> bump flutter to v3.3.5

- lib/service/substrate_api/core/js_api.dart
- pubspec.lock
- pubspec.yaml
I can say that the [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) package got better after upgrading its version, but I realized that our error 
```
E/flutter (17528): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_1214122967374174233124163190134233129107185174)
E/flutter (17528): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter (17528): <asynchronous suspension>
E/flutter (17528): #1      InAppWebViewController.evaluateJavascript (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:1420:16)
E/flutter (17528): <asynchronous …
```
> upgraded flutter in app web view package version

- lib/app.dart
- lib/config.dart
- lib/config.g.dart
- lib/main.dart
- lib/modules/splash/view/splash_view.dart
- lib/store/app.dart
- test/store/account_test.dart
- test/store/app_test.dart
- test/store/encointer/encointer_test.dart
- test/store/encointer/sub_stores/community_store/community_store_test.dart
- test/store/settings_test.dart
- test_driver/app.dart
I tried to fix #783  and #830 it as I understand it.
---------------------------------------------------------------------
1. Deleted StoreConfigExtensions.
2. Deleted constructor field `Config` from `WalletApp`. Use  `store.config`.
> Fix use the app config 02

- lib/page-encointer/ceremony_box/ceremony_box_service.dart
- lib/page-encointer/ceremony_box/ceremony_info.dart
- lib/page-encointer/ceremony_box/components/ceremony_schedule.dart
- lib/page-encointer/ceremony_box/components/ceremony_start_button.dart
- lib/page-encointer/ceremony_box/meetup_info/components/ceremony_location_button.dart
- lib/page-encointer/ceremony_box/meetup_info/meetup_info.dart
- lib/page-encointer/meetup/ceremony_step1_count.dart
- lib/page-encointer/meetup/ceremony_step2_scan2.dart
- lib/page-encointer/meetup/ceremony_step3_finish.dart
- lib/utils/translations/translations_encointer.dart
- lib/utils/translations/translations_profile.dart
Change translations into terms, which are socially less problematic, i.e., they are less associated with other contexts. 
meetup -> Gathering/Versammlung
ceremony -> Key-Signing Cycle
> Update translations for meetups and ceremonies

- ios/Podfile.lock
run IOS platform
`flutter doctor`
```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6 21G115 darwin-arm, locale ru-KG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```
> bump inApp_webView in PodFile.lock

- lib/page-encointer/ceremony_box/ceremony_box.dart
- lib/page-encointer/meetup/ceremony_step1_count.dart
- lib/page-encointer/meetup/ceremony_step2_scan2.dart
- lib/page-encointer/meetup/ceremony_step3_finish.dart
- lib/page-encointer/meetup/scan_claim_qr_code.dart
- lib/service/tx/lib/src/params.dart
- lib/service/tx/lib/src/submit_tx_wrappers.dart
- lib/store/encointer/encointer.dart
- lib/store/encointer/sub_stores/community_store/community_account_store/community_account_store.dart
- lib/store/encointer/sub_stores/community_store/community_account_store/community_account_store.g.dart
- lib/utils/translations/translations_encointer.dart
- test/store/encointer/sub_stores/community_store/community_account_store_test.dart
Changes:
* Use the new `attestAttendees` extrinsic after a meetup
* QR-Scanner understands plain addresses at meetups, but it still shows the full `ClaimOfAttendance` for backwards compatibility
* Add dev button to attest all meetup participants.
> Use new `attestAttendees` extrinsic

- lib/page-encointer/meetup/ceremony_step1_count.dart
- lib/page-encointer/meetup/ceremony_step2_scan2.dart
- lib/page-encointer/meetup/scan_claim_qr_code.dart
- lib/service/tx/lib/src/submit_tx_wrappers.dart
- lib/store/encointer/sub_stores/community_store/community_account_store/community_account_store.dart
- lib/store/encointer/sub_stores/community_store/community_account_store/community_account_store.g.dart
- lib/utils/translations/translations_encointer.dart
- test/store/encointer/sub_stores/community_store/community_account_store_test.dart
Changes:
In v1.8.9 a change was introduced when submitting the claim of attendances. This change introduced an error: Instead of the `vote` on how many participants are attending the meetup, we simply sent the number of scanned claims of attendance to the chain, which is `vote -1`. This does not lead to an invalid meetup, the checks allow for this discrepancy of one. However, this does not suffice as a condition for the early payout. So the early payout was broken with the version v1.8.9 and v1.8.10. This PR fixes that: Closes #866 
Show the new ClaimV2 instead of the old claim: This removes backwards compatibility with app versions ≤ v1.8.10. However, the blockchain fails to handle meetups with mixed app versions where one submit claims with `attestClaims` the other with …
> add correct vote to new `attestAttendees` extrinsic and remove backwards compatibility with old claims as the chain can't handle mixed setups.

- scripts/fdroid_init.sh
This removes the need of downloading xz-utils in the f-droid pipeline.
> [scdripts/fdroid-init] use gz extension instead of xz

- lib/app.dart
- lib/main.dart
- lib/modules/modules.dart
- lib/modules/settings/logic/app_settings_store.dart
- lib/modules/settings/logic/app_settings_store.g.dart
- lib/modules/settings/logic/settings_store.dart
- lib/modules/settings/logic/settings_store.g.dart
- lib/modules/settings/service/lang_service.dart
- lib/modules/settings/settings.dart
- lib/modules/settings/view/lang_page.dart
- lib/page/profile/index.dart
- lib/router/app_router.dart
- lib/utils/translations/index.dart
- test_driver/app.dart
- test_driver/app_test.dart
Yes I created new `AppSettings` because our `SettingsStore` and `AppStore` are very captivated by each other and when did little change app gave me more error 😓😓😓. I think we need to slowly divide our stores. How do you think?
Completed:
> Fix localization

- lib/common/components/address_input_field.dart
- lib/common/components/password_input_dialog.dart
- lib/page/assets/transfer/payment_confirmation_page/index.dart
- lib/page/assets/transfer/transfer_page.dart
- lib/page/profile/account/account_manage_page.dart
- lib/page/profile/account/export_result_page.dart
- lib/page/profile/contacts/contact_detail_page.dart
- lib/page/profile/contacts/contacts_page.dart
- lib/page/profile/index.dart
- test_driver/helpers/other_test.dart
- test_driver/real_app_test.dart
contact book. This newcomer shall register afterwards, and we want to test that he is an endorsee.
The transaction test is ready but it is tested not from `HomePage` but from `contact book page`. 
Because there is no default address from home page to transfer page and driver can't tap to drop `dropdown_search item`
This package was not tested integration (no key).
> Integration test

- lib/common/components/logo/community_icon.dart
- lib/page-encointer/common/community_chooser_on_map.dart
- lib/page/assets/index.dart
- lib/store/encointer/sub_stores/community_store/community_store.dart
- lib/store/encointer/sub_stores/community_store/community_store.g.dart
community-icon-IPFS-error
if I understood correctly this issue https://github.com/encointer/encointer-wallet-flutter/issues/912
I think it is fixed
```dart
final data = await webApi.ipfs.getCommunityIcon(assetsCid!);
communityIcon = data ?? (context != null ? await DefaultAssetBundle.of(context).loadString(fallBackCommunityIcon) : null);
return communityIcon;
```
if `ipfs.getCommunityIcon` return null or has error our `communityIcon` get from `assets` and `communityIcon` be is not null
> Improve handling of community icon

- README.md
- pubspec.lock
- pubspec.yaml
clean old flutter version run: `./flutterw clean` 
download new version run: `./flutterw pub get`
I think we can bump SDK version from `">=2.12.0 <3.0.0"` to `dart: ">=2.18.0 <3.0.0"` 
this allows us to use the new features of dart language but after testing this i will do another PR
> bump flutter v3.3.10

- .github/action-config.json
- .github/workflows/android_build.yml
- .github/workflows/android_integration_test.yml
- .github/workflows/ios_integration_test.yml
- .github/workflows/js_ci.yml
- .github/workflows/unit_tests.yml
- README.md
I decided to not overengineer stuff, and trade-off a bit of redundancy for simplicity. Closes #933.
No more deprecated warnings in the CI! Yaaay!
> [GA] Remove deprecated monorepo-actions/config-for-actions

- lib/service/tx/lib/src/submit_tx_wrappers.dart
> Fix display of buttons for non-newbies in dialog after registering

- lib/page/profile/account/account_manage_page.dart
- lib/page/profile/contacts/contact_detail_page.dart
- lib/service/tx/lib/src/submit_tx_wrappers.dart
* [contact_details_page] Closes #939
* [contact_details_page] Fix: Show cupertino activity indicator after tapping the endorse newcomer button
* [tx] better placement of educational dialog spacers
* [profile] prevent short-term red screen when deleting the current account
> only show endorse helper text if current account is not a bootstrapper

- .github/README.md
- .github/workflows/ios_integration_test.yml
This is sometimes needed when the GitHub Action Runners are updated. I have added a small Readme in the `.github` folder, which explains the reason and the fix.
> Update IOS runtimes for IPad simulator creation

- .github/README.md
- README.md
Somehow, github was unable to handle the readme in the `.github` folder. It has overwritten the one from the root of the repository.
> Move readme content from github folder into root readme

- README.md
- pubspec.lock
Changes:
* Make code snippets copyable by replacing '`' with '```'
* Add comment about `.flutter` submodule not being updated when it changed on remote
* Fix formatting and trailing whitespaces.
> Readme: Make code snippets copyable and add remark about outdated `.flutter` submodule

- README.md
- pubspec.lock
- pubspec.yaml
I migrated my other project to `impeller` with flutter version 3.7.1 but when i try in this project i have problem.
I noticed that the performance improves when I use `impeller`. that is  why I would like to try to use it in our `encointer_wallet` when the flutter skin version comes out. but this time there were some problems so I upgraded only flutter version without any other changes.
> Bump flutter v3.7.3

- app/lib/common/components/address_input_field.dart
- app/lib/js_service_encointer/src/service/account.js
- app/lib/service/substrate_api/account_api.dart
- app/lib/store/account/account.dart
- app/lib/store/account/account.g.dart
- app/lib/utils/format.dart
Before, the address input fields tried to look up onchain accounts. However, this feature is largely unnecessary IMO, as it needed a correct account id or account index to look up the account data on the blockchain. Further, the encointer blockchain does not even have the necessary pallet in the runtime.
So I removed all that code and simplified the address input field. Additionally, we can now filter by account name too.
> [AddressInputField] simplify code and and add account filtering based on name

- app/lib/page/network_select_page.dart
- app/lib/store/account/account.dart
- app/lib/store/account/account.g.dart
Changes:
* [NetworkSelectPage]: Remove the account creation button
* [NetworkSelectPage]: Finally fix the distorted icons display
* [NetworkSelectPage]: Remove handling of the account index, as it does not exist on encointer anyhow, for more info #1017.
> Simplify network select page and remove `accountIndexMap` from account store

- app/lib/page/network_select_page.dart
- Closes #1035.
Other Changes:
* [SettingsPage] Don't derive the the asset path from the network id. Instead, directly resolve the asset based on the current network and the network Id.
> Rename inconsistent icons in assets

- app/test_driver/app.dart
```console
E/flutter ( 3321): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_local@447310200' has not been initialized.
E/flutter ( 3321): #0      _local (package:timezone/src/env.dart)
E/flutter ( 3321): #1      local (package:timezone/src/env.dart:28:23)
E/flutter ( 3321): #2      _EncointerHomePageState.initState.<anonymous closure> (package:encointer_wallet/page-encointer/home_page.dart:39:12)
E/flutter ( 3321): <asynchronous suspension>
```
I noticed this error give only when we test  `test_driver/app.dart`. Because in `test_driver/app.dart` file we didn’t call `await NotificationPlugin.setup();`
* Closes #1037
> Fix timezone uninitialized warning in integration test

- README.md
I'm not happy with the README. not sure if this is really better yet, but I'd say we kick all the info out that is not strictily necessary
> simplify build setup instructions for ubuntu

- app/lib/page/profile/contacts/contact_detail_page.dart
- app/lib/router/app_router.dart
- app/test_driver/real_app_test.dart
User can change contact name
I used `StatefulWidget` widget so that I could use `setState` method.
I didn't refactor so PR wouldn't grow.
If you want, I can create `ContactsStore` for Contact pages and refactor UI codes or I can do another PR for refactoring.
* Closes #416
> Change contact name

- melos.yaml
- pubspec.lock
- pubspec.yaml
I got error like this from `github tests` and i was very surprised. 
And i found out it has to do with `melos`.
[see more about migrations](https://melos.invertase.dev/guides/migrations)
```console
Run ./flutterw pub global run melos bootstrap
./flutterw pub global run melos bootstrap
shell: /bin/bash -e {0}
env:
NODE_VERSION: 16.13.1
JAVA_VERSION: 1[2](https://github.com/encointer/encointer-wallet-flutter/actions/runs/4383959347/jobs/7674846517#step:10:2).x
TEMP_SCREENSHOTS: /tmp/screenshots
JAVA_HOME: /Users/runner/hostedtoolcache/Java_Zulu_jdk/12.0.2-[3](https://github.com/encointer/encointer-wallet-flutter/actions/runs/4383959347/jobs/7674846517#step:10:3)/x6[4](https://github.com/encointer/encointer-wallet-flutter/actions/runs/4383959347/jobs/7674846517#step:10:4)
JAVA_HOME_12_X64: …
```
> Upgrade melos v3.0.0

- .github/workflows/check_labels.yml
CI now enforces on (non-draft) PRs at least one label of each category listed below:
- A label (change type):
- `A0-ux`
- `A1-bugfix`
- `A2-technical`
- B label (urgency):
- `B0-low`
- `B1-medium`
- `B2-critical`
- C label (breaking changes)
- `C0-breaksnothing`
- `C1-breaksapi`
part of https://github.com/encointer/encointer-wallet-flutter/issues/705
@clangenb  please check the newly introduced labels as well.
Tested:
> Add CI label check

- app/lib/page/profile/account/account_manage_page.dart
- app/test_driver/helpers/other_test.dart
- app/test_driver/real_app_test.dart
Some times real app integration test give error for axample:
```console
11:01 +31 -1: delete all account ad show create account page
VMServiceFlutterDriver: tap message is taking a long time to complete...
11:31 +31 -2: delete all account ad show create account page [E]
TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
package:test_api/src/backend/invoker.dart 334:28  Invoker._handleError.<fn>
dart:async/zone.dart 1390:47                      _rootRun
dart:async/zone.dart 1300:19                      _CustomZone.run
package:test_api/src/backend/invoker.dart 332:10  Invoker._handleError
package:test_api/src/backend/invoker.dart 288:9   Invoker.heartbeat.<fn>.<fn>
dart:async/zone.dart 1398:13                      _rootRun …
```
> Fix flaky integration test: share and change account name

- app/lib/service/notification/lib/src/notification_plugin.dart
I noticed we don’t use some methods(screams), we do nothing when give local notification and user select notification.
I tested real app integration test everything ✅  :).
If you agree with me I can merge to my `el/gbd-notification-sound`.
> Remove unused methods and vars in NotificationPlugin

- app/js_service_encointer/src/service/account.js
- app/js_service_encointer/src/service/settings.js
- app/lib/config/consts.dart
- app/lib/mocks/substrate_api/mock_encointer_api.dart
- app/lib/models/ceremonies/ceremonies.dart
- app/lib/page-encointer/meetup/ceremony_step2_scan2.dart
- app/lib/page-encointer/meetup/scan_claim_qr_code.dart
- app/lib/service/substrate_api/account_api.dart
- app/lib/service/substrate_api/encointer/encointer_api.dart
- app/lib/service/tx/lib/src/submit_tx_wrappers.dart
- app/lib/store/encointer/encointer.dart
- app/lib/utils/format.dart
After merging this PR, the addresses will start with a letter when we are connected to the Kusama network, e.g. `Alice: HNZata7iMYWmk5RvZRTiAsSDhV8366zq2YGb3tLH5Upf74F`. When we are connected to all other networks Gesell, Gesell-dev, Rococo the addresses will still start with a 5, e.g. `Alice: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY`.
* Closes #567: We now pass the pubKey into the dart RPC-API and always derive the address with prefix 42.
* Closes #1019 by implementing the last open subtask.
Tests:
Voucher should be unaffected as the QR-code is based on the secret seed.
> Remove ss58-prefix override and use the network-specific prefix for address display

- .vscode/launch.json
Added configurations for Android and iOS in launch.json.
From now on, in order to run project on iOS, no need to comment `args`, just choose iOS and run it.
> [launch.json] distinguished configuration for Android and iOS

- app/android/app/build.gradle
- app/android/app/src/main/AndroidManifest.xml
- app/android/app/src/main/kotlin/org/encointer/wallet/MainActivity.kt
* Closes #1050
It was crashing because the `java.time` package was added only in API 26 and above. Older phones still tried to call this API and thus it crashed. Adding `ThreeTenABP` resolves the issue.
This PR introduces the change to use `ThreeTenABP` for Android API < 26 and `java.time` in otherwise.
> Fixed app crash on Android API < 26

- app/lib/common/components/launch/send_to_trello_list_tile.dart
Sending bug report to `bugreports@mail.encointer.org` instead of troll board
* Closes #1192
> Forward mail to bugreports instead of trello directly

- app/lib/config.dart
- app/lib/page/assets/transfer/payment_confirmation_page/index.dart
I think this will be useful for us. If the application is running for an integration test, it won't repeatedly execute the animate check. If it's in normal mode, it will continue to work as before.
`PaymentConfirmationPage` and animate seemed very complex to me. But since this PR is not about refactoring, I didn't do anything. It was just a small PR that completed the task. But if you want, I can do the refactoring.
* Closes #1114
> TxConfirmPage printscreen should have the tick visible

- app/lib/modules/transfer/logic/transfer_history_view_store.dart
- app/lib/modules/transfer/widgets/transaction_card.dart
Tried to fix fitting of TransfersPage on small devices. Bug was noticed on iphone8 which  has a 4.7-inch screen with a screen size (resolution): | 750px × 1334px |.
if the `getNameFromContacts` cannot fit within the given space, it will be truncated with an ellipsis (...) at the end.
Tested on android emulator size Nexus 4 |  4,7" | 768x1280px | 
on Iphone SE  | 750 x 1334px | 
Also I used [device_preview](https://pub.dev/packages/device_preview) package to test on even smaller device   | 360 x 640 px|
Closes #1287
> UI Bug v1.10.0: Autofitting of Transfers Screen for small devices doesn't work

- app/lib/modules/settings/logic/app_settings_store.dart
- app/lib/modules/settings/service/app_service.dart
With my previous corrections, a bug has emerged. If the user didn't select a language, the application was supposed to set its language based on the device's language.
| Before initial locale | After initial locale |
|--------|--------|
| ![Simulator Screenshot - iPhone 14 Pro Max - 2023-06-24 at 11 15 27](https://github.com/encointer/encointer-wallet-flutter/assets/76556278/84d8ebb7-ca04-4283-a30d-9747000004a9) | ![Simulator Screenshot - iPhone 14 Pro Max - 2023-06-24 at 11 20 41](https://github.com/encointer/encointer-wallet-flutter/assets/76556278/854b9e22-099d-49f8-b184-28f1d8dded3c)|
> Fix: Initialize the locale with system language 

- app/lib/page-encointer/new_bazaar/businesses/widgets/businesses_card.dart
* Constraint business titles to one line. Closes #1346
> [Bazaar] fix businesses padding

- app/lib/page/assets/announcement/logic/announcement_store.dart
- app/lib/page/assets/announcement/logic/announcement_store.g.dart
- app/lib/page/assets/announcement/view/announcement_view.dart
The error occurred because `https://encointer.github.io/feed/dev/{cid/global}/{de/fr/ru}/announcements.json` is missing from our feed repo.
* Closes #1352
> Remove announcement error dialog

- app/lib/common/components/animation/animated_check.dart
- app/lib/page/assets/transfer/payment_confirmation_page/index.dart
- app/pubspec.lock
- app/pubspec.yaml
Very old package code integrated to dart 3
See package https://pub.dev/packages/animated_check (last update 21 months ago)
* Closes #1269
> Remove old package `animated_check` and implement it ourselves

- app/lib/modules/login/service/login_service.dart
- app/lib/modules/settings/service/app_service.dart
- app/test_driver/helpers/command/app_functions.dart
I haven't had a chance to test it, but I think that solves our problem. 
* Closes #1353
> Asks enabling biometric authentication although I already enabled it previously

- app/lib/models/transfer/transfer_history.dart
- app/lib/modules/transfer/widgets/transaction_card.dart
* Closes #1356
Other minor changes:
* Fix: use counterparty as source for the address icon instead of own account
* enable tap to copy address from counterparty to facilitate simple import into contacts.
> [transfer_history] fix display names of contacts created pre-1.9.1

- app/lib/page-encointer/meetup/scan_claim_qr_code.dart
I don't know if it was because we manually set the text size before, but the text size didn't change according to the device settings. Now it changes according to device settings. 
If I understand the task correctly, the task is done.
* Closes #1355
> adjust `scannedAttendeesCount` according to device settings

- app/lib/models/transfer/transfer_history.dart
- app/lib/modules/transfer/logic/transfer_history_view_store.dart
- app/lib/modules/transfer/widgets/transaction_card.dart
- app/lib/modules/transfer/widgets/transactions_list.dart
Although I did not manage to reproduce #1392 successfully, the first occurrence was after https://github.com/encointer/encointer-wallet-flutter/pull/1376. So I am quite confident, that address decoding failed at some point. Hence, I made the transfer list more robust by handling errors during that process, hoping that it will resolve that issue.
* Closes #1392
> More robust transfer history

- app/test/store/bazaar/businesses_store_test.dart
Nothing really was broken, since we use `sortedBusinesses` in UI, changed it for unit test as well.
- Closes: #1374
> update bazaar business store unit test to match business logic

- app/lib/common/components/animation/animated_check.dart
- app/lib/page/assets/transfer/payment_confirmation_page/index.dart
When the transfer was successful, we used to get an animation error when we clicked "done"  for back. With this PR, we don't get any animation error anymore. :)
```console
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 772 pos 7: '_ticker != null': AnimationController.stop() called after AnimationController.dispose()
animation_controller.dart:772
AnimationController methods should not be used after calling dispose.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      AnimationController.stop
animation_controller.dart:772
#3      AnimationController.value=
animation_controller.dart:361
#4 …
```
> Fix: `TransferPage` animation controller error

- app/lib/common/components/qr_code_view/qr_code_image_view.dart
- app/lib/page-encointer/meetup/ceremony_step2_scan2.dart
- app/lib/page/assets/qr_code_printing/pages/qr_code_share_or_print_view.dart
- app/lib/page/assets/receive/receive_page.dart
* Closes #1454 
Finally, we introduce a scrollable view here, which, I assume, wasn't done before because the QrCode had problems defining its own size, which it has to if it should be put into a list view.
https://github.com/encointer/encointer-wallet-flutter/assets/37865735/3af48bc0-1fe8-411a-9a75-a52c82c348e7
> Fix display of QR-code for big font sizes and small screens

- app/js_service_encointer/package.json
- app/js_service_encointer/src/service/account.js
- app/js_service_encointer/src/service/encointer.js
- app/js_service_encointer/src/utils/utils.js
- app/js_service_encointer/test/utils/utils.test.js
- app/js_service_encointer/yarn.lock
- app/lib/service/tx/lib/src/submit_to_js.dart
An API change in BN.js v5 lead to potential encoding issues. The catchy thing here was that we depend on Bn.js v4, which encodes correctly, but for some (non-deterministic) reason, webpack sometimes resolves to v5, and then we got an encoding error as our bitlength setting was ignored.
Another notable change introduced is that we now try-catch the whole extrinsic sending process - I thought this would fix the endless activity indicators while sending an extrinsic, but it seems that they still occurr.
Failing IOS tests seem to occur on all branches now, and it seems unrelated to this PR: #1485
> Fix potential encoding errors for EncointerBalances and catch ALL errors while sending extrinsics

- .github/workflows/android_integration_test.yml
- .github/workflows/ios_integration_test.yml
- scripts/ios_emulator.sh
This PR is an attempt to fix the lately unstable IOS CI. The update changed the available predefined simulators; hence I took the time to revisit the latest specifications for the mandatory printscreens to publish the app on all IOS devices: https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications/.
It seems that the CI is still unstable unfortunately, but the update was needed anyhow.
> [GHA] use macos-13 runner image and update IOS Simulators

- app/js_service_encointer/src/service/account.js
I did this to better understand what happens in the transaction send process for implementing #1474, but it is also a first step for that task, as we can reuse the the creation of the signed xt in the dart extrinsic sender later.
> [JS] separate the creation of a signed extrinsic from its send process.

- app/lib/common/components/logo/community_icon.dart
- app/lib/page/assets/index.dart
- app/test_driver/app/home/home_test.dart
I think this is more intuitive, and it also allows as to wait in tests until all frames have been rendered. I think, this was part of the flaky integration tests, as we didn't wait until the app was in a stable state in tests.
> show default community icon instead of activity indicator when no community is selected

- app/lib/service/substrate_api/api.dart
Sometimes the home page was in a weird state after changing the network: no info in the ceremony box, many activity indicators. I noticed that this is because basic network info is still null like `phaseDurations`, `nextPhaseTimestamp`, and for some reason the observer didn't pick up when they become non-null.
I couldn't find the reason why the observer didn't pick it up, so the quick-fix was to just wait until the values are set in the init function.
> Get basic encointer network params in initialization of webView

- .github/workflows/android_integration_test.yml
They have been unstable for a long time, and completely broken since we started using macos 13, as the emulator couldn't start up. This PR reverts the change to macos-13, and uses now Android Api 33, which seems to be stable so far.
> Fix android device tests; use macos 12 runners and switch to api level 33

- .github/workflows/android_build.yml
- .github/workflows/android_integration_test.yml
- .github/workflows/ios_integration_test.yml
- .github/workflows/unit_tests.yml
- README.md
- melos.yaml
- pubspec.lock
- pubspec.yaml
- scripts/android_integration_test.sh
- scripts/install_melos.sh
- scripts/ios_integration_test.sh
- scripts/multi_language_screenshot_ci_test.sh
I had some issues on my machine with melos. When I debugged I noticed, that we can improve our setup by using the projects melos all the time instead of the globally installed one.
Benefits:
* Ensure that we have the same melos version on different machines
* Simplify commands and remove hacks
Note: Make sure to install the project dependencies once with pub get to ensure that you use the project's melos instead of the global one.
> bump melos and always use the project's melos instead of the global one

- app/lib/service/substrate_api/api.dart
In #1529, when we started sending txs with dart, I implemented all the fundamentals to try to reconnect upon each request if we are disconnected, but I forgot to actually call that check in the `send` and `subscription` methods. This should make our send process much more stable.
It is difficult to say, as I don't have the exact logs, but I think it closes #1546.
> fix: reconnecting websocket checks connection state on each request

- app/lib/service/substrate_api/encointer/encointer_api.dart
- app/pubspec.lock
- packages/ew_keyring/pubspec.lock
- packages/ew_polkadart/pubspec.lock
They fixed the storage hash generation upstream: https://github.com/leonardocustodio/polkadart/pull/375
> Bump polkadart and remove hack for wrongly generated storage key

- app/lib/service/substrate_api/chain_api.dart
- app/lib/store/chain/types/header.dart
https://github.com/encointer/encointer-wallet-flutter/pull/1570 has introduced a change in the de-serialization of the `latestHeader`, which fails when the latest header is read from cache. As this is used upon app-startup, the app couldn't start anymore.
The bug was introduced by this change: https://github.com/encointer/encointer-wallet-flutter/pull/1570/files#r1410622103
> fix app startup: remove broken chain store cache

- app/lib/page/profile/account/account_manage_page.dart
* Closes #1584 as a side-effect.
> Show non-zero balances of all prevously chosen communities in non-dev mode

- app/lib/service/substrate_api/chain_api.dart
- app/lib/store/chain/chain.dart
- app/lib/store/chain/types/header.dart
- app/lib/store/chain/types/header.g.dart
- app/lib/store/settings.dart
The ordering of operations when changing the network has not been quite correct and some parts were missing, leading for instance to #1601.
* Closes #1601.
> Fix switching networks

- app/lib/models/ceremonies/ceremonies.dart
- app/lib/page/profile/account/faucet_list_tile.dart
- app/lib/page/profile/contacts/contact_detail_page.dart
- app/lib/page/profile/index.dart
- app/lib/service/substrate_api/encointer/encointer_api.dart
- app/lib/store/encointer/sub_stores/encointer_account_store/encointer_account_store.dart
- app/lib/store/encointer/sub_stores/encointer_account_store/encointer_account_store.g.dart
We tried to drip the faucet with a `UnverifiedReputable` reputation, as we couldn't find reputation commitments for it, and the app considered it to be good enough for dripping the faucet. This PR implements a change such that we only consider verified reputations for claiming the faucet, which is how it should be. Closes #1608.
> Fix potential `NoReputation` error in faucet.

- app/lib/common/components/address_input_field.dart
- app/lib/page/assets/transfer/transfer_page.dart
- app/lib/page/profile/account/change_password_page.dart
- app/lib/page/profile/account/export_account_page.dart
- app/lib/service/substrate_api/account_api.dart
- app/lib/store/account/account.dart
- app/lib/store/account/types/account_data.dart
- app/lib/store/account/types/account_data.g.dart
Minor improvement extracted from #1614
> Properly define `AccountData` for more ergonomic usage

- app/js_service_encointer/src/service/account.js
- app/lib/modules/account/logic/new_account_result.dart
- app/lib/modules/account/logic/new_account_store.dart
- app/lib/modules/account/logic/new_account_store.g.dart
- app/lib/modules/account/view/import_account_view.dart
- app/lib/service/substrate_api/account_api.dart
- app/lib/store/account/account.dart
- app/lib/store/account/account.g.dart
- app/lib/store/app.dart
- app/test/store/account_test.dart
- packages/ew_keyring/lib/src/keyring.dart
- packages/ew_keyring/lib/src/keyring_account.dart
- packages/ew_keyring/lib/src/keyring_utils.dart
Most account handling is already in dart since #1614, but we have still been creating them in JS, and then we extracted the seeds. Now we also create them in dart, and then import them into JS, where they are still used to sign extrinsics.
* Closes #1520
* Closes #1480
* Closes #606
* Closes #478, but only because it will be detected later, while sending extrinsics, that the webView has not been instantiated successfully.
> Create accounts in dart instead of JS

- app/js_service_encointer/src/service/account.js
- app/js_service_encointer/src/service/chain.js
- app/js_service_encointer/src/service/encointer.js
- app/js_service_encointer/src/utils/utils.js
- app/lib/l10n/arb/app_de.arb
- app/lib/l10n/arb/app_en.arb
- app/lib/l10n/arb/app_fr.arb
- app/lib/l10n/arb/app_ru.arb
- app/lib/page/reap_voucher/dialogs.dart
- app/lib/page/reap_voucher/reap_voucher_page.dart
- app/lib/router/app_router.dart
- app/lib/service/substrate_api/account_api.dart
- app/lib/service/substrate_api/chain_api.dart
- app/lib/service/tx/lib/src/submit_tx_wrappers.dart
* Closes #1580, only sending is still done in JS, which will be solved with #1540.
This also fixes a previously unknown issue that changing the network or the cid from the reap voucher page was hanging in an endless loop.
> [ReapVoucher] Minor refactoring and move reap voucher prechecks from JS to dart

- app/lib/modules/account/logic/key_type.dart
- app/lib/modules/account/logic/new_account_result.dart
- app/lib/modules/account/logic/new_account_store.dart
- app/lib/modules/account/logic/new_account_store.g.dart
- app/lib/modules/account/view/add_account_view.dart
- app/lib/modules/account/view/create_account_view.dart
- app/lib/modules/account/view/create_pin_view.dart
- app/lib/modules/account/view/handle_new_account_result_mixin.dart
- app/lib/modules/account/view/import_account_view.dart
- app/lib/modules/login/logic/login_store.dart
- app/lib/modules/login/service/login_service.dart
- app/lib/modules/login/view/login_dialog.dart
- app/lib/page/profile/account/change_password_page.dart
I was about to investigate #1496, where I noticed that the account importing and the PIN querying was much more complicated and obfuscated than necessary (to be fair, parts of the simplifications were only possible after #1618).
Summary of changes:
* Remove responsibility of the `NewAccountStore` to also query the pin, as it is not even needed anymore to create new accounts. Simply ask for the PIN if not cached on the Create/Import page. Closes #1496.
* There were unnecessary calls to `setPin` in cases where we only wanted to (runtime-)cache the PIN, but `setPin` actually persists them to the secure storage. I removed all cases of `setPIN` except for when actually setting the PIN or changing the PIN.
> Improve PIN handling for creating and importing accounts

- app/lib/service/tx/lib/src/submit_tx_wrappers.dart
- app/pubspec.lock
- packages/ew_encointer_utils/pubspec.lock
- packages/ew_keyring/pubspec.lock
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/balances.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/collective.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/dmp_queue.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/encointer_balances.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/encointer_bazaar.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/encointer_ceremonies.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/encointer_communities.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/encointer_faucet.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/encointer_reputation_commitments.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/encointer_scheduler.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/membership.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/parachain_system.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/polkadot_xcm.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/proxy.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/scheduler.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/system.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/timestamp.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/treasury.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/utility.dart
- packages/ew_polkadart/lib/generated/encointer_kusama/pallets/xcmp_queue.dart
- packages/ew_polkadart/pubspec.lock
- packages/ew_primitives/pubspec.lock
Bump polkadart to get PR https://github.com/leonardocustodio/polkadart/pull/409, and regenerate types afterwards.
This gives us compile time type safety, before those types were implicitly dynamic.
> Bump polkadart to get type safety in extrinsic call api

- app/lib/page/assets/index.dart
- app/lib/store/encointer/encointer.dart
- app/lib/store/encointer/sub_stores/encointer_account_store/encointer_account_store.dart
- app/lib/store/encointer/sub_stores/encointer_account_store/encointer_account_store.g.dart
This removes the kind of hacky balance watchdog we had implemented. The reason is that it was for some reason very slow to update, and that showing the notifications of incoming balance diffs was broken anyhow since some flutter update. I suggest re-introducing this notification with the indexer instead, such that we can actually show incoming transfers instead of incoming balance diffs, https://github.com/encointer/encointer-wallet-flutter/issues/1656. Also, this fixes the jumping balance after a network switch. Closes #1530.
I integrated the periodic update of the encointer balance into the overall state update. As the balance update is now blazingly fast, I simplified the getter to only fetch the balance for the currently chosen community instead of getting the non-zero balances of all …
> Fix: Refresh balance immediately after starting the app for the first time and when adding a new account

- app/lib/service/tx/lib/src/send_tx_dart.dart
- app/lib/service/tx/lib/src/submit_tx_wrappers.dart
- app/lib/service/tx/lib/src/tx_builder.dart
This PR implements the idea from https://github.com/encointer/encointer-wallet-flutter/issues/1659#issuecomment-2008617012. In the signed extension, we use now the latest finalized block hash instead of the best block hash. This indeed fixes the invalid transaction if it is resubmitted from a retracted block. I did some extensive testing, namely did multiple meetups and sent arbitrary transactions, to ensure with high probability that the issue is fixed.
Closes #1659.
> Fix app stale at sending extrinsics aka fix occasional invalid extrinsic

- app/lib/page/assets/announcement/widgets/announcement_card.dart
- app/pubspec.lock
- app/pubspec.yaml
There is a test message in the dev feed that shows how it works: https://github.com/encointer/feed/commit/e03ae976f71aa20aec999e086e94b35e8e2ec95c. This dev message is displayed in dev mode.
Closes #1666
Follow-up issue to have more customizability with links: https://github.com/encointer/encointer-wallet-flutter/issues/1669
> [Announcements] parse links in community announcements and open the browser upon tapping

- .github/workflows/ios_integration_test.yml
- app/lib/main.dart
- app/lib/page/assets/index.dart
- app/lib/service/init_web_api/init_web_api.dart
- app/lib/service/substrate_api/api.dart
- app/lib/service/substrate_api/core/dart_api.dart
- app/lib/service/substrate_api/core/reconnecting_ws_provider.dart
- app/lib/service/substrate_api/encointer/encointer_api.dart
- app/lib/service/substrate_api/encointer/encointer_dart_api.dart
- app/lib/store/settings.dart
- app/test/mock/api/mock_api.dart
- app/test/mock/api/mock_substrate_dart_api.dart
- app/test/service/substrate_api/core/dart_api_test.dart
- app/test/service/substrate_api/encointer/encointer_dart_api_test.dart
Improvements:
* Add a periodic background check to see if we are still connected, and reconnect if disconnected. This background check only runs when the app is in the foreground.
* Fix switching the network if we are disconnected. Closes #1667, closes #1670.
* Simplify connection management by only using one websocket for all node connections.
> Periodic websocket connection check and fix network switch when the app is disconnected

- app/android/app/build.gradle
- app/android/app/src/main/AndroidManifest.xml
- app/lib/service/notification/lib/src/ceremony_notifications.dart
- app/lib/service/notification/lib/src/notification_plugin.dart
- app/pubspec.lock
- app/pubspec.yaml
* For some reason, we didn't check if notification permissions were given on Android. This is now checked upon startup and the user is prompted to allow notifications.
* Fix android manifest to show scheduled permissions and to persist scheduled notifications after a reboot
* Android > 13 doesn't allow exact scheduling of notifications, which resulted in an error.  We simply relaxed our scheduling to inexact, as we are not building a precise alarm app.
> Fix notifications on Android

- app/lib/page-encointer/democracy/widgets/proposal_tile.dart
Closes #1715. 
Solution, simply hide the misleading texts in case there is 0 turnout. See:
> [Democracy] fix proposal initial value sanitation

- packages/ew_substrate_fixed/lib/src/to_fixed_point.dart
- packages/ew_substrate_fixed/test/to_fixed_point_test.dart
This is a preparation for #1751, where we need to transform double values to locations (before, we used it only the other way round).
> support negative double to fixed point conversion

- app/lib/l10n/arb/app_de.arb
- app/lib/l10n/arb/app_en.arb
- app/lib/l10n/arb/app_fr.arb
- app/lib/l10n/arb/app_ru.arb
- app/lib/l10n/arb/app_sw.arb
- app/lib/page-encointer/democracy/proposal_page/propose_page.dart
* Closes #1758.
* Tested manually that:
> [proposePage] only bootstrappers or reputables can submit a proposal

- app/lib/l10n/arb/app_de.arb
- app/lib/l10n/arb/app_en.arb
- app/lib/l10n/arb/app_fr.arb
- app/lib/l10n/arb/app_ru.arb
- app/lib/l10n/arb/app_sw.arb
- app/lib/page-encointer/democracy/proposal_page/helpers.dart
- app/lib/page-encointer/democracy/proposal_page/propose_page.dart
- app/lib/service/substrate_api/encointer/encointer_api.dart
- app/lib/service/tx/lib/src/submit_to_inner.dart
- packages/ew_polkadart/lib/encointer_types.dart
We now check on the submit proposals type if there is already a proposal pending enactment of the currently selected proposal action it. If there is, we show a message, and disable the submit button. Related issue #1761.
> Prevent submitting new proposals of a proposal type already pending enactment

- app/lib/page-encointer/democracy/proposal_page/helpers.dart
- app/lib/page-encointer/democracy/proposal_page/propose_page.dart
- app/test/page_encointer/democracy/proposal_page/helpers.dart
Before this check did not take into account the community as a scope. Now it correctly checks:
* Disallow sending proposals for: same proposal id && same scope
> [proposePage] fix: disallow sending same proposal for same scope

- app/lib/page-encointer/democracy/proposal_page/propose_page.dart
- app/lib/page-encointer/democracy/proposal_page/utf8_limited_byte_field.dart
The reason why this did not work before was that `text.codeunits` returns utf16 instead of utf8 values. This is fixed now, and we also introduced a byte counter in the text field, which prevents exceeding the 256 byte limit. Closes #1766.
> [proposePage] properly limit the text size for the petition field and show current byte count

- app/lib/common/components/launch/send_to_trello_list_tile.dart
- app/lib/config/consts.dart
- app/lib/l10n/arb/app_de.arb
- app/lib/l10n/arb/app_en.arb
- app/lib/l10n/arb/app_fr.arb
- app/lib/l10n/arb/app_ru.arb
- app/lib/l10n/arb/app_sw.arb
- app/lib/page-encointer/ceremony_box/ceremony_box.dart
- app/lib/page-encointer/ceremony_box/components/unregister_link_button.dart
- app/lib/page-encointer/democracy/proposal_page/propose_page.dart
- app/lib/page-encointer/meetup/ceremony_step3_finish.dart
- app/lib/page/assets/index.dart
- app/lib/page/profile/account/faucet_list_tile.dart
- app/lib/page/profile/account/remark.dart
- app/lib/page/profile/contacts/contact_detail_page.dart
- app/lib/service/tx/lib/src/submit_to_inner.dart
The bug was very simple, we simply popped too fast so that we never saw the dialog. Additionally, there is no a field in the txErrorDialog to submit bug reports. In most cases this is hidden, as it is most likely a user error, but if it is a transaction format error, the button is shown.
* Closes #1761
> [proposePage] correctly show the txErrorDialog if there was an error 

- app/lib/page-encointer/democracy/proposal_page/propose_page.dart
- app/lib/page-encointer/democracy/widgets/update_proposal_button.dart
- app/lib/page-encointer/democracy/widgets/vote_button.dart
- app/lib/service/tx/lib/src/submit_to_inner.dart
- packages/ew_polkadart/lib/runtime_error.dart
* The fix consists of two parts:
* Don't pop the error dialog too early so that we cannot see the dialog
* Add the new error definitions from the democracy pallet. (They need manual generaction as polkadart does not support generating that automatically yet.)
Other minor fix:
* We correctly hinted that we cannot submit a proposal if the same type/scope is already pending enactment, but we forgot to disable the button correspondingly. Now we disable the button too.
> [democracyPage] fix: display democracy errors

- app/lib/page-encointer/democracy/helpers.dart
- app/lib/page-encointer/democracy/proposal_page/propose_page.dart
#1779 already tried to fix the `IssueSwapNative` rate in the proposal, but it applied the decimals into the wrong direction, leading to the `SwapOverflow` error observed in #1773.
This PR does now properly apply the fix, and it has been end-to-end tested on a local setup:
* Issue Swap Native Option: Exchange up to 10 KSM at a rate of 0.1
* Redeem 5 KSM → Properly deducted ~0.5 KSM. 👍
> [democracy] fix rate in swap native proposal (this time for real)

- app/android/app/build.gradle
* This PR actually fixes what we tried to achieve with the flutter update, see #1809.
The flutter ndk is on version 26, but as the ndk versions are backwards compatible this should not be an issue, and the app works locally.
> Build with ndk28; support 16KB memory page size
